 **Calculation Morgan fingerprints and usage xgb**

In [1]:
import time
t0start = time.time() 

from rdkit import Chem
from rdkit.Chem import AllChem, DataStructs
import numpy as np
import pandas as pd

In [3]:
import warnings
warnings.filterwarnings('ignore')

In [4]:
df = pd.read_csv('df.csv')
df

            MP                                             SMILES
0       355.15                           O=[N+]([O-])c1c(O)cccc1O
1       373.65  Cc1c([N+](=O)[O-])cc([N+](=O)[O-])c(N(C)[N+](=...
2       373.75                  O=c1ccc([N+](=O)[O-])cn1Cc1ccccc1
3       373.70    N#CC(Cc1ccccc1)(Cc1ccco1)c1ccc([N+](=O)[O-])cc1
4       374.25      CCOC(=O)c1cc2ccccc2cc1-c1ccc([N+](=O)[O-])cc1
...        ...                                                ...
117747  395.65          BrC1=CC2=C(C=C1)N=C(O2)C1=CC=CC=C1N(=O)=O
117748  396.15      C[C@@H]1CC(=O)C[C@@H](N1)C1=CC=C(C=C1)N(=O)=O
117749  327.65                          O=N(=O)C1=C(OCC#N)C=CC=C1
117750  488.15    O=N(=O)C1=CC(=C(NN=C\C=C\C2=CC=CO2)C=C1)N(=O)=O
117751  389.15  CC(C)(C)OC(=O)N[C@H](CN(=O)=O)C1=CC=C(C=C1)N(=...

[117752 rows x 2 columns]

In [5]:
%%time
fingerprints = []
    
from rdkit.Chem import AllChem
from rdkit.Chem import rdFingerprintGenerator

# Create a Morgan fingerprint generator
morgan_generator = rdFingerprintGenerator.GetMorganGenerator(radius=2, fpSize=2048)
for smi in df["SMILES"]:
    mol = Chem.MolFromSmiles(smi)
    fp = morgan_generator.GetFingerprint(mol) 
    arr = np.array(fp)
    fingerprints.append(arr)

CPU times: user 8min 34s, sys: 3.22 s, total: 8min 38s
Wall time: 8min 41s

In [5]:
len(fingerprints[0])

2048

In [7]:
X_morgan = pd.DataFrame(np.array(fingerprints))
X_morgan

,0,1,2,3,4,5,6,7,8,9,...,2038,2039,2040,2041,2042,2043,2044,2045,2046,2047
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117747,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
117748,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
117749,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
117750,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
117751,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
%%time
fingerprints3 = []

morgan_generator = rdFingerprintGenerator.GetMorganGenerator(radius=3, fpSize=2048)
for smi in df["SMILES"]:
    mol = Chem.MolFromSmiles(smi)
    fp = morgan_generator.GetFingerprint(mol) 
    arr = np.array(fp)
    fingerprints3.append(arr)

CPU times: user 6min 50s, sys: 3.03 s, total: 6min 53s
Wall time: 6min 56s

In [8]:
len(fingerprints3[0])

2048

In [8]:
X_morgan3 = pd.DataFrame(np.array(fingerprints3))
X_morgan3

,0,1,2,3,4,5,6,7,8,9,...,2038,2039,2040,2041,2042,2043,2044,2045,2046,2047
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117747,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
117748,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
117749,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
117750,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
117751,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
emb_morgan_df = pd.concat([X_morgan, X_morgan3], ignore_index=True, axis=1)
emb_morgan_df

,0,1,2,3,4,5,6,7,8,9,...,4086,4087,4088,4089,4090,4091,4092,4093,4094,4095
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117747,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
117748,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
117749,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
117750,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
117751,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
mps = [mp for mp in df["MP"]]
len(mps)

117752

In [11]:
emb_morgan_df["MP"] = mps
emb_morgan_df

,0,1,2,3,4,5,6,7,8,9,...,4087,4088,4089,4090,4091,4092,4093,4094,4095,MP
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,355.15
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,373.65
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,373.75
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,373.70
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,374.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117747,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,395.65
117748,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,396.15
117749,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,327.65
117750,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,488.15
117751,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,389.15

In [13]:
emb_morgan_df.to_csv('emb_morgan_df.csv', index=False)

In [2]:
emb_morgan_df = pd.read_csv('emb_morgan_df.csv')
emb_morgan_df

,0,1,2,3,4,5,6,7,8,9,...,4087,4088,4089,4090,4091,4092,4093,4094,4095,MP
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,355.15
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,373.65
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,373.75
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,373.70
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,374.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117747,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,395.65
117748,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,396.15
117749,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,327.65
117750,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,488.15
117751,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,389.15

In [13]:
from sklearn.model_selection import train_test_split
X_mor_train, X_mor_test, Y_train, Y_test = train_test_split(emb_morgan_df.iloc[:, :-1], emb_morgan_df.iloc[:, -1], test_size=0.2, random_state=42)

In [4]:
import xgboost as xgb
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [15]:
%%time
model = xgb.XGBRegressor(n_estimators=1000, n_jobs=-1, learning_rate=0.01, max_depth=7)

model.fit(X_mor_train, Y_train)

Y_pred = model.predict(X_mor_test)

mse = mean_squared_error(Y_test, Y_pred)
mse = mean_squared_error(Y_test, Y_pred)
rmse = mse ** 0.5
mae = mean_absolute_error(Y_test, Y_pred)
r2 = r2_score(Y_test, Y_pred)

print(f"MSE: {mse}, RMSE: {rmse}, MAE: {mae}, R²: {r2}")

MSE: 1872.0777161148094, RMSE: 43.2675134034163, MAE: 33.29790458005587, R²: 0.631792546259337
CPU times: user 17h 1min 43s, sys: 50min 32s, total: 17h 52min 15s
Wall time: 55min 18s

In [16]:
print(f"MSE: {mse:.2f}, RMSE: {rmse:.2f}, MAE: {mae:.2f}, R²: {r2:.2f}")

MSE: 1872.08, RMSE: 43.27, MAE: 33.30, R²: 0.63

In [11]:
emb_morgan_df

,0,1,2,3,4,5,6,7,8,9,...,4087,4088,4089,4090,4091,4092,4093,4094,4095,MP
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,355.15
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,373.65
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,373.75
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,373.70
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,374.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117747,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,395.65
117748,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,396.15
117749,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,327.65
117750,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,488.15
117751,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,389.15

In [ ]:
%%time

import numpy as np
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error, mean_absolute_error

X = emb_morgan_df.iloc[:, :-1]
y = emb_morgan_df.iloc[:, -1]

n_folds = 5
kf = KFold(n_splits=n_folds, shuffle=True, random_state=42)

maes = []
rmsses = []

for train_idx, val_idx in kf.split(X):
    X_train, y_train = X.iloc[train_idx], y.iloc[train_idx]
    X_val, y_val = X.iloc[val_idx], y.iloc[val_idx]
    
    model = xgb.XGBRegressor(
        n_estimators=1000,
        n_jobs=-1,
        learning_rate=0.05,
        max_depth=7
    )
    model.fit(X_train, y_train)

    y_pred = model.predict(X_val)
    
    mse = mean_squared_error(y_val, y_pred)
    rmse = np.sqrt(mse)
    
    mae = mean_absolute_error(y_val, y_pred)

    rmsses.append(rmse)
    maes.append(mae)

mean_mae = np.mean(maes)
std_mae = np.std(maes)
mean_rmse = np.mean(rmsses)
std_rmse = np.std(rmsses)

print(f'MAE: {mean_mae:.4f} ± {std_mae:.4f}')
print(f'RMSE: {mean_rmse:.4f} ± {std_rmse:.4f}')

In [ ]:
rmses

In [10]:
maes

[30.223800691787545,
 30.33479798697065,
 29.892133739673177,
 30.566746657982655,
 30.143653819637617]

In [12]:
print(f'MAE: {mean_mae:.4f} ± {std_mae:.4f}')
print(f'RMSE: {mean_rmse:.4f} ± {std_rmse:.4f}')

MAE: 30.2322 ± 0.2218
RMSE: 39.8475 ± 0.3997