In [1]:
import sys

In [2]:
sys.path.append('/data02/tabm')

In [3]:
# ruff: noqa: E402
import math
import random
import warnings
from typing import Literal, NamedTuple

import numpy as np
import pandas as pd
import rtdl_num_embeddings  # https://github.com/yandex-research/rtdl-num-embeddings
import scipy.special
import sklearn.datasets
import sklearn.metrics
import sklearn.model_selection
import sklearn.preprocessing
import torch
import torch.nn.functional as F
import torch.optim
from torch import Tensor
from tqdm.std import tqdm

warnings.simplefilter('ignore')
from tabm_reference import Model, make_parameter_groups

warnings.resetwarnings()

ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

In [ ]:
import torchvision

In [5]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

NameError: name 'torch' is not defined

In [16]:
df_cb = pd.read_csv('chem_bert_emb_df.csv')
df_cb

,0,2,3,4,5,6,7,8,9,10,...,590,591,592,593,594,595,596,597,598,599
0,0.383230,0.517380,-0.280701,0.008003,0.219609,0.726157,-0.362477,-0.405935,0.430935,-0.859224,...,0.088762,-0.032460,0.060221,0.710166,0.107282,-0.070665,-0.364548,0.524827,-0.219044,0.296993
1,0.053002,0.046581,-0.045467,0.265602,0.121656,0.248467,-0.471550,-0.289988,-0.205801,-0.737166,...,0.241539,0.247456,-0.045622,0.724922,0.419859,-0.171350,-0.007923,0.040881,0.082113,0.109209
2,0.650106,1.011580,0.463880,-0.496643,0.410833,0.831479,0.182609,-0.388742,-0.045355,-0.275201,...,-0.128667,-0.135553,0.645528,-0.111434,0.043732,0.342703,0.008101,0.571934,0.079836,-0.283608
3,-0.209592,-0.243905,0.176476,0.517554,0.026938,-0.402658,-0.327484,-0.280088,-0.028855,-0.180202,...,-0.035334,-0.285914,-0.212273,0.117536,0.522993,-0.621208,0.539129,0.111357,0.331581,-0.086567
4,0.122910,-0.064467,0.686867,0.239316,-0.103160,-0.167726,-0.105149,-0.489707,-0.066420,-0.162347,...,-0.030928,-0.134271,-0.102144,0.248343,0.010503,0.611926,0.318152,-0.114292,0.528896,0.231508
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117747,0.217291,0.508175,-0.111223,0.113894,0.382003,0.612502,-0.328363,-0.080576,-0.240976,0.293184,...,-0.045533,0.423016,0.121292,-0.209866,0.408977,0.190961,-0.239830,0.351643,0.320553,-0.202831
117748,-0.067462,0.677433,-0.245434,0.440785,0.263820,0.551249,-0.395648,-0.091693,-0.263357,-0.179503,...,0.316211,0.689446,0.232293,-0.200617,0.187333,0.386570,-0.406295,0.402920,0.360022,-0.122600
117749,0.181496,0.512077,-0.280476,0.437974,-0.027109,0.723539,-0.385805,-0.248053,-0.145493,0.086625,...,-0.096264,0.213210,0.422839,0.372862,0.592165,0.328713,-0.316499,0.294498,0.418610,-0.106374
117750,-0.098858,0.585181,-0.392476,0.777918,0.295732,0.250359,-0.306643,0.118758,-0.226906,-0.079321,...,0.182980,0.544464,0.256705,0.045325,0.412411,0.184333,-0.314178,-0.058447,0.660162,-0.180543
117751,0.033644,0.599846,-0.234451,0.553492,0.294395,0.216537,-0.238240,0.011329,-0.016467,-0.226111,...,0.277145,0.506719,0.112179,-0.074024,0.264317,0.325658,-0.337432,-0.028559,0.557561,-0.184028

In [17]:
df = pd.read_csv('df.csv')
mps = [mp for mp in df['MP']]
df_cb['MP'] = mps
df_cb

,0,2,3,4,5,6,7,8,9,10,...,591,592,593,594,595,596,597,598,599,MP
0,0.383230,0.517380,-0.280701,0.008003,0.219609,0.726157,-0.362477,-0.405935,0.430935,-0.859224,...,-0.032460,0.060221,0.710166,0.107282,-0.070665,-0.364548,0.524827,-0.219044,0.296993,355.15
1,0.053002,0.046581,-0.045467,0.265602,0.121656,0.248467,-0.471550,-0.289988,-0.205801,-0.737166,...,0.247456,-0.045622,0.724922,0.419859,-0.171350,-0.007923,0.040881,0.082113,0.109209,373.65
2,0.650106,1.011580,0.463880,-0.496643,0.410833,0.831479,0.182609,-0.388742,-0.045355,-0.275201,...,-0.135553,0.645528,-0.111434,0.043732,0.342703,0.008101,0.571934,0.079836,-0.283608,373.75
3,-0.209592,-0.243905,0.176476,0.517554,0.026938,-0.402658,-0.327484,-0.280088,-0.028855,-0.180202,...,-0.285914,-0.212273,0.117536,0.522993,-0.621208,0.539129,0.111357,0.331581,-0.086567,373.70
4,0.122910,-0.064467,0.686867,0.239316,-0.103160,-0.167726,-0.105149,-0.489707,-0.066420,-0.162347,...,-0.134271,-0.102144,0.248343,0.010503,0.611926,0.318152,-0.114292,0.528896,0.231508,374.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117747,0.217291,0.508175,-0.111223,0.113894,0.382003,0.612502,-0.328363,-0.080576,-0.240976,0.293184,...,0.423016,0.121292,-0.209866,0.408977,0.190961,-0.239830,0.351643,0.320553,-0.202831,395.65
117748,-0.067462,0.677433,-0.245434,0.440785,0.263820,0.551249,-0.395648,-0.091693,-0.263357,-0.179503,...,0.689446,0.232293,-0.200617,0.187333,0.386570,-0.406295,0.402920,0.360022,-0.122600,396.15
117749,0.181496,0.512077,-0.280476,0.437974,-0.027109,0.723539,-0.385805,-0.248053,-0.145493,0.086625,...,0.213210,0.422839,0.372862,0.592165,0.328713,-0.316499,0.294498,0.418610,-0.106374,327.65
117750,-0.098858,0.585181,-0.392476,0.777918,0.295732,0.250359,-0.306643,0.118758,-0.226906,-0.079321,...,0.544464,0.256705,0.045325,0.412411,0.184333,-0.314178,-0.058447,0.660162,-0.180543,488.15
117751,0.033644,0.599846,-0.234451,0.553492,0.294395,0.216537,-0.238240,0.011329,-0.016467,-0.226111,...,0.506719,0.112179,-0.074024,0.264317,0.325658,-0.337432,-0.028559,0.557561,-0.184028,389.15

In [18]:
res_df = df_cb

res_df

,0,2,3,4,5,6,7,8,9,10,...,591,592,593,594,595,596,597,598,599,MP
0,0.383230,0.517380,-0.280701,0.008003,0.219609,0.726157,-0.362477,-0.405935,0.430935,-0.859224,...,-0.032460,0.060221,0.710166,0.107282,-0.070665,-0.364548,0.524827,-0.219044,0.296993,355.15
1,0.053002,0.046581,-0.045467,0.265602,0.121656,0.248467,-0.471550,-0.289988,-0.205801,-0.737166,...,0.247456,-0.045622,0.724922,0.419859,-0.171350,-0.007923,0.040881,0.082113,0.109209,373.65
2,0.650106,1.011580,0.463880,-0.496643,0.410833,0.831479,0.182609,-0.388742,-0.045355,-0.275201,...,-0.135553,0.645528,-0.111434,0.043732,0.342703,0.008101,0.571934,0.079836,-0.283608,373.75
3,-0.209592,-0.243905,0.176476,0.517554,0.026938,-0.402658,-0.327484,-0.280088,-0.028855,-0.180202,...,-0.285914,-0.212273,0.117536,0.522993,-0.621208,0.539129,0.111357,0.331581,-0.086567,373.70
4,0.122910,-0.064467,0.686867,0.239316,-0.103160,-0.167726,-0.105149,-0.489707,-0.066420,-0.162347,...,-0.134271,-0.102144,0.248343,0.010503,0.611926,0.318152,-0.114292,0.528896,0.231508,374.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117747,0.217291,0.508175,-0.111223,0.113894,0.382003,0.612502,-0.328363,-0.080576,-0.240976,0.293184,...,0.423016,0.121292,-0.209866,0.408977,0.190961,-0.239830,0.351643,0.320553,-0.202831,395.65
117748,-0.067462,0.677433,-0.245434,0.440785,0.263820,0.551249,-0.395648,-0.091693,-0.263357,-0.179503,...,0.689446,0.232293,-0.200617,0.187333,0.386570,-0.406295,0.402920,0.360022,-0.122600,396.15
117749,0.181496,0.512077,-0.280476,0.437974,-0.027109,0.723539,-0.385805,-0.248053,-0.145493,0.086625,...,0.213210,0.422839,0.372862,0.592165,0.328713,-0.316499,0.294498,0.418610,-0.106374,327.65
117750,-0.098858,0.585181,-0.392476,0.777918,0.295732,0.250359,-0.306643,0.118758,-0.226906,-0.079321,...,0.544464,0.256705,0.045325,0.412411,0.184333,-0.314178,-0.058447,0.660162,-0.180543,488.15
117751,0.033644,0.599846,-0.234451,0.553492,0.294395,0.216537,-0.238240,0.011329,-0.016467,-0.226111,...,0.506719,0.112179,-0.074024,0.264317,0.325658,-0.337432,-0.028559,0.557561,-0.184028,389.15

In [20]:
res_df.to_csv('chem_bert_emb_df.csv', index=False)

In [ ]:
# >>> Dataset.
TaskType = Literal['regression', 'binclass', 'multiclass']

# Regression.
task_type: TaskType = 'regression'
n_classes = None
dataset = res_df
X_cont: np.ndarray = res_df.iloc[:, :-1].to_numpy()
Y: np.ndarray = res_df.iloc[:, -1].to_numpy()

task_is_regression = task_type == 'regression'

# >>> Continuous features.
X_cont: np.ndarray = X_cont.astype(np.float32)
n_cont_features = X_cont.shape[1]

# >>> Labels.
if task_type == 'regression':
    Y = Y.astype(np.float32)
else:
    assert n_classes is not None
    Y = Y.astype(np.int64)
    assert set(Y.tolist()) == set(
        range(n_classes)
    ), 'Classification labels must form the range [0, 1, ..., n_classes - 1]'

# >>> Split the dataset.
all_idx = np.arange(len(Y))
trainval_idx, test_idx = sklearn.model_selection.train_test_split(
    all_idx, train_size=0.8
)
train_idx, val_idx = sklearn.model_selection.train_test_split(
    trainval_idx, train_size=0.8
)
data_numpy = {
    'train': {'x_cont': X_cont[train_idx], 'y': Y[train_idx]},
    'val': {'x_cont': X_cont[val_idx], 'y': Y[val_idx]},
    'test': {'x_cont': X_cont[test_idx], 'y': Y[test_idx]},
}

X_cont_train_numpy = data_numpy['train']['x_cont']
noise = (
    np.random.default_rng(0)
    .normal(0.0, 1e-5, X_cont_train_numpy.shape)
    .astype(X_cont_train_numpy.dtype)
)
preprocessing = sklearn.preprocessing.QuantileTransformer(
    n_quantiles=max(min(len(train_idx) // 30, 1000), 10),
    output_distribution='normal',
    subsample=10**9,
).fit(X_cont_train_numpy + noise)
del X_cont_train_numpy

# Apply the preprocessing.
for part in data_numpy:
    data_numpy[part]['x_cont'] = preprocessing.transform(data_numpy[part]['x_cont'])


# Label preprocessing.
class RegressionLabelStats(NamedTuple):
    mean: float
    std: float


Y_train = data_numpy['train']['y'].copy()
if task_type == 'regression':
    # For regression tasks, it is highly recommended to standardize the training labels.
    regression_label_stats = RegressionLabelStats(
        Y_train.mean().item(), Y_train.std().item()
    )
    Y_train = (Y_train - regression_label_stats.mean) / regression_label_stats.std
else:
    regression_label_stats = None

data = {
    part: {k: torch.as_tensor(v, device=device) for k, v in data_numpy[part].items()}
    for part in data_numpy
}

Y_train = torch.as_tensor(Y_train, device=device)
if task_type == 'regression':
    for part in data:
        data[part]['y'] = data[part]['y'].float()
    Y_train = Y_train.float()
    
amp_dtype = (
    torch.bfloat16
    if torch.cuda.is_available() and torch.cuda.is_bf16_supported()
    else torch.float16
    if torch.cuda.is_available()
    else None
)
# Changing False to True will result in faster training on compatible hardware.
amp_enabled = False and amp_dtype is not None
grad_scaler = torch.cuda.amp.GradScaler() if amp_dtype is torch.float16 else None  # type: ignore

# torch.compile
compile_model = False

# fmt: off
print(
    f'Device:        {device.type.upper()}'
    f'\nAMP:           {amp_enabled} (dtype: {amp_dtype})'
    f'\ntorch.compile: {compile_model}'
)
# fmt: on

In [42]:
print('\n\nResult:')
print(best)

Result:
{'val': -36.008947320206055, 'test': -36.450139518230074, 'epoch': 153}

In [26]:
df_um = pd.read_csv('uni-mol.csv')
df_um

,0,1,2,3,4,5,6,7,8,9,...,503,504,505,506,507,508,509,510,511,MP
0,-0.013992,-0.669688,-0.810371,-0.820527,-0.944870,-1.545177,1.004045,0.720911,-0.538595,1.131984,...,0.365982,1.061863,-2.759452,1.193249,-0.218466,0.379487,2.335730,0.893357,-2.023531,355.15
1,-0.255941,-0.482257,-0.014340,-0.300146,-0.454813,-1.467290,0.742272,0.779284,-0.378655,1.614774,...,0.528400,0.815105,-2.774471,1.246665,0.295793,-0.397826,2.357099,0.496361,-2.069937,373.65
2,-0.116311,-0.716807,-0.596487,-0.134767,-0.437958,-1.901230,1.060897,0.929643,-0.660413,1.297815,...,0.430205,0.736438,-2.816033,1.252844,0.396341,-0.504774,2.235858,0.548843,-2.080271,373.75
3,-0.094511,-0.824312,-0.569022,-0.392049,-0.464151,-1.441643,0.799341,0.841834,-0.314347,1.312179,...,0.576383,0.337680,-2.739552,1.275348,0.565805,-0.853423,2.139378,0.804444,-2.055217,373.70
4,-0.291880,-0.746322,-0.622199,-0.409220,-0.443025,-1.259129,0.990855,0.646626,-0.346968,1.213809,...,0.606900,0.408470,-2.747625,1.222448,0.677137,-0.627984,2.115620,0.872131,-2.057241,374.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117747,-0.073738,-0.700036,-0.405322,-0.244470,-0.489630,-1.644408,0.836901,0.682566,-0.335481,1.285728,...,0.198654,0.263748,-2.825043,1.211132,0.321607,-0.647005,2.305871,0.891368,-2.107719,395.65
117748,-0.146027,-0.864437,-0.300155,-0.259133,-0.658427,-1.554542,0.857640,0.988294,-0.525199,1.286521,...,0.699391,0.257819,-2.783286,1.274370,0.355458,-0.614098,2.207493,0.802195,-2.024621,396.15
117749,0.096798,-1.041117,-0.263131,-0.502725,-0.931887,-1.409036,0.755577,0.720619,-0.723526,1.525824,...,0.449580,1.015750,-2.798421,1.329739,0.094653,-0.600728,2.345972,0.610362,-2.006141,327.65
117750,-0.367869,-0.537741,-0.650870,-0.120295,-0.444859,-1.763567,1.131350,0.718563,-0.293059,1.283509,...,0.286710,0.295653,-2.660894,1.250393,0.357552,-0.294115,2.211480,0.837793,-2.026178,488.15
117751,-0.342744,-0.844379,-0.408003,-0.183939,-0.594973,-1.481225,1.055992,0.550893,-0.862702,1.483937,...,0.540263,0.303420,-2.667953,1.195595,0.214852,-0.748405,2.151342,0.838102,-1.986376,389.15

In [27]:
# >>> Dataset.
TaskType = Literal['regression', 'binclass', 'multiclass']

# Regression.
task_type: TaskType = 'regression'
n_classes = None
dataset = df_um
X_cont: np.ndarray = df_um.iloc[:, :-1].to_numpy()
Y: np.ndarray = df_um.iloc[:, -1].to_numpy()

task_is_regression = task_type == 'regression'

# >>> Continuous features.
X_cont: np.ndarray = X_cont.astype(np.float32)
n_cont_features = X_cont.shape[1]

# >>> Labels.
if task_type == 'regression':
    Y = Y.astype(np.float32)
else:
    assert n_classes is not None
    Y = Y.astype(np.int64)
    assert set(Y.tolist()) == set(
        range(n_classes)
    ), 'Classification labels must form the range [0, 1, ..., n_classes - 1]'

# >>> Split the dataset.
all_idx = np.arange(len(Y))
trainval_idx, test_idx = sklearn.model_selection.train_test_split(
    all_idx, train_size=0.8
)
train_idx, val_idx = sklearn.model_selection.train_test_split(
    trainval_idx, train_size=0.8
)
data_numpy = {
    'train': {'x_cont': X_cont[train_idx], 'y': Y[train_idx]},
    'val': {'x_cont': X_cont[val_idx], 'y': Y[val_idx]},
    'test': {'x_cont': X_cont[test_idx], 'y': Y[test_idx]},
}

X_cont_train_numpy = data_numpy['train']['x_cont']
noise = (
    np.random.default_rng(0)
    .normal(0.0, 1e-5, X_cont_train_numpy.shape)
    .astype(X_cont_train_numpy.dtype)
)
preprocessing = sklearn.preprocessing.QuantileTransformer(
    n_quantiles=max(min(len(train_idx) // 30, 1000), 10),
    output_distribution='normal',
    subsample=10**9,
).fit(X_cont_train_numpy + noise)
del X_cont_train_numpy

# Apply the preprocessing.
for part in data_numpy:
    data_numpy[part]['x_cont'] = preprocessing.transform(data_numpy[part]['x_cont'])


# Label preprocessing.
class RegressionLabelStats(NamedTuple):
    mean: float
    std: float


Y_train = data_numpy['train']['y'].copy()
if task_type == 'regression':
    # For regression tasks, it is highly recommended to standardize the training labels.
    regression_label_stats = RegressionLabelStats(
        Y_train.mean().item(), Y_train.std().item()
    )
    Y_train = (Y_train - regression_label_stats.mean) / regression_label_stats.std
else:
    regression_label_stats = None

data = {
    part: {k: torch.as_tensor(v, device=device) for k, v in data_numpy[part].items()}
    for part in data_numpy
}

Y_train = torch.as_tensor(Y_train, device=device)
if task_type == 'regression':
    for part in data:
        data[part]['y'] = data[part]['y'].float()
    Y_train = Y_train.float()
    
amp_dtype = (
    torch.bfloat16
    if torch.cuda.is_available() and torch.cuda.is_bf16_supported()
    else torch.float16
    if torch.cuda.is_available()
    else None
)
# Changing False to True will result in faster training on compatible hardware.
amp_enabled = False and amp_dtype is not None
grad_scaler = torch.cuda.amp.GradScaler() if amp_dtype is torch.float16 else None  # type: ignore

# torch.compile
compile_model = False

# fmt: off
print(
    f'Device:        {device.type.upper()}'
    f'\nAMP:           {amp_enabled} (dtype: {amp_dtype})'
    f'\ntorch.compile: {compile_model}'
)
# fmt: on

Device:        CUDA
AMP:           False (dtype: torch.bfloat16)
torch.compile: False

In [28]:
# Choose one of the two configurations below.

# TabM
arch_type = 'tabm'
bins = None

model = Model(
    n_num_features=n_cont_features,
    cat_cardinalities=[], # zero categorical data
    n_classes=n_classes,
    backbone={
        'type': 'MLP',
        'n_blocks': 3 if bins is None else 2,
        'd_block': 512,
        'dropout': 0.1,
    },
    bins=bins,
    num_embeddings=(
        None
        if bins is None
        else {
            'type': 'PiecewiseLinearEmbeddings',
            'd_embedding': 16,
            'activation': False,
            'version': 'B',
        }
    ),
    arch_type=arch_type,
    k=32,
    share_training_batches=True,
).to(device)
optimizer = torch.optim.AdamW(make_parameter_groups(model), lr=2e-3, weight_decay=3e-4)

if compile_model:
    # NOTE
    # `torch.compile` is intentionally called without the `mode` argument
    # (mode="reduce-overhead" caused issues during training with torch==2.0.1).
    model = torch.compile(model)
    evaluation_mode = torch.no_grad
else:
    evaluation_mode = torch.inference_mode
    
@torch.autocast(device.type, enabled=amp_enabled, dtype=amp_dtype)  # type: ignore[code]
def apply_model(part: str, idx: Tensor) -> Tensor:
    return (
        model(
            data[part]['x_cont'][idx],
            data[part]['x_cat'][idx] if 'x_cat' in data[part] else None,
        )
        .squeeze(-1)  # Remove the last dimension for regression tasks.
        .float()
    )


base_loss_fn = F.mse_loss if task_type == 'regression' else F.cross_entropy


def loss_fn(y_pred: Tensor, y_true: Tensor) -> Tensor:
    # TabM produces k predictions. Each of them must be trained separately.
    # (regression)     y_pred.shape == (batch_size, k)
    # (classification) y_pred.shape == (batch_size, k, n_classes)
    k = y_pred.shape[-1 if task_type == 'regression' else -2]
    return base_loss_fn(
        y_pred.flatten(0, 1),
        y_true.repeat_interleave(k) if model.share_training_batches else y_true,
    )


@evaluation_mode()
def evaluate(part: str) -> float:
    model.eval()

    # When using torch.compile, you may need to reduce the evaluation batch size.
    eval_batch_size = 8096
    y_pred: np.ndarray = (
        torch.cat(
            [
                apply_model(part, idx)
                for idx in torch.arange(len(data[part]['y']), device=device).split(
                    eval_batch_size
                )
            ]
        )
        .cpu()
        .numpy()
    )
    if task_type == 'regression':
        # Transform the predictions back to the original label space.
        assert regression_label_stats is not None
        y_pred = y_pred * regression_label_stats.std + regression_label_stats.mean

    # Compute the mean of the k predictions.
    if task_type != 'regression':
        # For classification, the mean must be computed in the probabily space.
        y_pred = scipy.special.softmax(y_pred, axis=-1)
    y_pred = y_pred.mean(1)

    y_true = data[part]['y'].cpu().numpy()
    mae = sklearn.metrics.mean_absolute_error(y_true, y_pred)
    print(f'MAE ({part} set): {mae:.4f}')  # [ADDED MAE PRINT]
    score = (
        -(sklearn.metrics.mean_squared_error(y_true, y_pred) ** 0.5)
        if task_type == 'regression'
        else sklearn.metrics.accuracy_score(y_true, y_pred.argmax(1))
    )
    return float(score)  # The higher -- the better.


print(f'Test score before training: {evaluate("test"):.4f}')

MAE (test set): 55.9930
Test score before training: -71.3111

In [29]:
%time
n_epochs = 1_000_000_000
patience = 16

train_size = len(train_idx)
batch_size = 256
epoch_size = math.ceil(train_size / batch_size)
best = {
    'val': -math.inf,
    'test': -math.inf,
    'epoch': -1,
}
# Early stopping: the training stops when
# there are more than `patience` consequtive bad updates.
patience = 16
remaining_patience = patience

print('-' * 88 + '\n')
for epoch in range(n_epochs):
    batches = (
        torch.randperm(train_size, device=device).split(batch_size)
        if model.share_training_batches
        else [
            x.transpose(0, 1).flatten()
            for x in torch.rand((model.k, train_size), device=device)
            .argsort(dim=1)
            .split(batch_size, dim=1)
        ]
    )
    for batch_idx in tqdm(batches, desc=f'Epoch {epoch}'):
        model.train()
        optimizer.zero_grad()
        loss = loss_fn(apply_model('train', batch_idx), Y_train[batch_idx])
        if grad_scaler is None:
            loss.backward()
            optimizer.step()
        else:
            grad_scaler.scale(loss).backward()  # type: ignore
            grad_scaler.step(optimizer)
            grad_scaler.update()

    val_score = evaluate('val')
    test_score = evaluate('test')
    print(f'(val) {val_score:.4f} (test) {test_score:.4f}')

    if val_score > best['val']:
        print('🌸 New best epoch! 🌸')
        best = {'val': val_score, 'test': test_score, 'epoch': epoch}
        remaining_patience = patience
    else:
        remaining_patience -= 1

    if remaining_patience < 0:
        break

    print()

print('\n\nResult:')
print(best)

CPU times: user 7 µs, sys: 0 ns, total: 7 µs
Wall time: 13.8 µs
----------------------------------------------------------------------------------------

Epoch 0: 100%|██████████| 295/295 [00:03<00:00, 82.46it/s]

MAE (val set): 33.6626
MAE (test set): 33.3756
(val) -43.2836 (test) -43.0816
🌸 New best epoch! 🌸

Epoch 1: 100%|██████████| 295/295 [00:02<00:00, 102.66it/s]

MAE (val set): 33.1481
MAE (test set): 33.0004
(val) -42.4757 (test) -42.3713
🌸 New best epoch! 🌸

Epoch 2: 100%|██████████| 295/295 [00:05<00:00, 53.59it/s]

MAE (val set): 32.3311
MAE (test set): 32.1446
(val) -41.6946 (test) -41.4744
🌸 New best epoch! 🌸

Epoch 3: 100%|██████████| 295/295 [00:03<00:00, 84.19it/s]

MAE (val set): 31.7155
MAE (test set): 31.4627
(val) -41.1653 (test) -40.9597
🌸 New best epoch! 🌸

Epoch 4: 100%|██████████| 295/295 [00:03<00:00, 95.11it/s]

MAE (val set): 32.1606
MAE (test set): 31.9896
(val) -41.6389 (test) -41.3840

Epoch 5: 100%|██████████| 295/295 [00:02<00:00, 108.07it/s]

MAE (val set): 31.8455
MAE (test set): 31.7442
(val) -41.2615 (test) -41.0861

Epoch 6: 100%|██████████| 295/295 [00:03<00:00, 89.71it/s]

MAE (val set): 31.3825
MAE (test set): 31.2784
(val) -40.6143 (test) -40.4715
🌸 New best epoch! 🌸

Epoch 7: 100%|██████████| 295/295 [00:02<00:00, 102.42it/s]

MAE (val set): 31.0254
MAE (test set): 30.8707
(val) -40.3858 (test) -40.2012
🌸 New best epoch! 🌸

Epoch 8: 100%|██████████| 295/295 [00:03<00:00, 98.21it/s]

MAE (val set): 31.3845
MAE (test set): 31.2557
(val) -40.7732 (test) -40.5678

Epoch 9: 100%|██████████| 295/295 [00:03<00:00, 83.54it/s]

MAE (val set): 31.1261
MAE (test set): 30.9827
(val) -40.2268 (test) -40.0598
🌸 New best epoch! 🌸

Epoch 10: 100%|██████████| 295/295 [00:02<00:00, 102.82it/s]

MAE (val set): 30.7299
MAE (test set): 30.5586
(val) -40.1614 (test) -39.9639
🌸 New best epoch! 🌸

Epoch 11: 100%|██████████| 295/295 [00:03<00:00, 96.40it/s]

MAE (val set): 30.8000
MAE (test set): 30.5886
(val) -39.8910 (test) -39.6658
🌸 New best epoch! 🌸

Epoch 12: 100%|██████████| 295/295 [00:03<00:00, 85.38it/s]

MAE (val set): 30.8076
MAE (test set): 30.7127
(val) -40.2577 (test) -40.0703

Epoch 13: 100%|██████████| 295/295 [00:03<00:00, 97.04it/s]

MAE (val set): 30.5115
MAE (test set): 30.3534
(val) -39.6260 (test) -39.4538
🌸 New best epoch! 🌸

Epoch 14: 100%|██████████| 295/295 [00:03<00:00, 80.92it/s]

MAE (val set): 30.6214
MAE (test set): 30.4659
(val) -39.6996 (test) -39.4781

Epoch 15: 100%|██████████| 295/295 [00:03<00:00, 90.80it/s]

MAE (val set): 30.4686
MAE (test set): 30.3426
(val) -39.6457 (test) -39.4293

Epoch 16: 100%|██████████| 295/295 [00:03<00:00, 86.09it/s]

MAE (val set): 30.3339
MAE (test set): 30.1593
(val) -39.3897 (test) -39.2226
🌸 New best epoch! 🌸

Epoch 17: 100%|██████████| 295/295 [00:03<00:00, 81.71it/s]

MAE (val set): 30.7864
MAE (test set): 30.7218
(val) -39.6481 (test) -39.6111

Epoch 18: 100%|██████████| 295/295 [00:04<00:00, 71.98it/s]

MAE (val set): 30.6439
MAE (test set): 30.5457
(val) -39.8072 (test) -39.6359

Epoch 19: 100%|██████████| 295/295 [00:03<00:00, 94.12it/s]

MAE (val set): 30.2660
MAE (test set): 30.2924
(val) -39.7025 (test) -39.5901

Epoch 20: 100%|██████████| 295/295 [00:02<00:00, 103.08it/s]

MAE (val set): 30.1274
MAE (test set): 30.0227
(val) -39.4348 (test) -39.2635

Epoch 21: 100%|██████████| 295/295 [00:03<00:00, 89.35it/s]

MAE (val set): 30.2324
MAE (test set): 30.1717
(val) -39.3892 (test) -39.2620
🌸 New best epoch! 🌸

Epoch 22: 100%|██████████| 295/295 [00:02<00:00, 111.07it/s]

MAE (val set): 30.4006
MAE (test set): 30.3217
(val) -39.2807 (test) -39.2076
🌸 New best epoch! 🌸

Epoch 23: 100%|██████████| 295/295 [00:03<00:00, 96.70it/s]

MAE (val set): 30.0885
MAE (test set): 29.9502
(val) -39.3152 (test) -39.1188

Epoch 24: 100%|██████████| 295/295 [00:02<00:00, 99.74it/s]

MAE (val set): 30.1900
MAE (test set): 30.1084
(val) -39.1861 (test) -39.0616
🌸 New best epoch! 🌸

Epoch 25: 100%|██████████| 295/295 [00:02<00:00, 102.88it/s]

MAE (val set): 30.1034
MAE (test set): 29.9855
(val) -39.1973 (test) -39.0424

Epoch 26: 100%|██████████| 295/295 [00:02<00:00, 100.15it/s]

MAE (val set): 29.8536
MAE (test set): 29.7695
(val) -39.0859 (test) -38.9219
🌸 New best epoch! 🌸

Epoch 27: 100%|██████████| 295/295 [00:02<00:00, 108.89it/s]

MAE (val set): 29.9506
MAE (test set): 29.7946
(val) -39.1151 (test) -38.9376

Epoch 28: 100%|██████████| 295/295 [00:03<00:00, 88.86it/s]

MAE (val set): 30.2312
MAE (test set): 30.1530
(val) -39.2496 (test) -39.0942

Epoch 29: 100%|██████████| 295/295 [00:02<00:00, 118.53it/s]

MAE (val set): 29.7688
MAE (test set): 29.5877
(val) -38.9150 (test) -38.7329
🌸 New best epoch! 🌸

Epoch 30: 100%|██████████| 295/295 [00:03<00:00, 98.11it/s]

MAE (val set): 29.7044
MAE (test set): 29.4997
(val) -38.8966 (test) -38.7059
🌸 New best epoch! 🌸

Epoch 31: 100%|██████████| 295/295 [00:02<00:00, 139.03it/s]

MAE (val set): 29.8647
MAE (test set): 29.7563
(val) -38.9048 (test) -38.7715

Epoch 32: 100%|██████████| 295/295 [00:02<00:00, 126.51it/s]

MAE (val set): 29.6328
MAE (test set): 29.5803
(val) -38.7784 (test) -38.6582
🌸 New best epoch! 🌸

Epoch 33: 100%|██████████| 295/295 [00:02<00:00, 135.84it/s]

MAE (val set): 29.9782
MAE (test set): 29.9448
(val) -39.1643 (test) -39.0077

Epoch 34: 100%|██████████| 295/295 [00:02<00:00, 138.62it/s]

MAE (val set): 29.9051
MAE (test set): 29.8135
(val) -38.9529 (test) -38.7894

Epoch 35: 100%|██████████| 295/295 [00:02<00:00, 123.79it/s]

MAE (val set): 29.7469
MAE (test set): 29.6298
(val) -38.7749 (test) -38.6649
🌸 New best epoch! 🌸

Epoch 36: 100%|██████████| 295/295 [00:02<00:00, 99.36it/s]

MAE (val set): 29.6222
MAE (test set): 29.4699
(val) -38.8051 (test) -38.6139

Epoch 37: 100%|██████████| 295/295 [00:04<00:00, 67.49it/s]

MAE (val set): 29.8759
MAE (test set): 29.8039
(val) -38.8729 (test) -38.7783

Epoch 38: 100%|██████████| 295/295 [00:03<00:00, 95.87it/s]

MAE (val set): 29.9057
MAE (test set): 29.8586
(val) -38.9188 (test) -38.8070

Epoch 39: 100%|██████████| 295/295 [00:03<00:00, 95.57it/s]

MAE (val set): 29.9612
MAE (test set): 29.8842
(val) -39.2500 (test) -39.0681

Epoch 40: 100%|██████████| 295/295 [00:02<00:00, 116.44it/s]

MAE (val set): 29.5400
MAE (test set): 29.4305
(val) -38.6600 (test) -38.4840
🌸 New best epoch! 🌸

Epoch 41: 100%|██████████| 295/295 [00:03<00:00, 88.09it/s]

MAE (val set): 29.6301
MAE (test set): 29.5231
(val) -38.7352 (test) -38.5297

Epoch 42: 100%|██████████| 295/295 [00:02<00:00, 103.54it/s]

MAE (val set): 29.5511
MAE (test set): 29.4930
(val) -38.5808 (test) -38.5085
🌸 New best epoch! 🌸

Epoch 43: 100%|██████████| 295/295 [00:02<00:00, 101.72it/s]

MAE (val set): 29.7520
MAE (test set): 29.7014
(val) -38.8793 (test) -38.7279

Epoch 44: 100%|██████████| 295/295 [00:02<00:00, 98.85it/s]

MAE (val set): 29.7057
MAE (test set): 29.6423
(val) -38.8940 (test) -38.7632

Epoch 45: 100%|██████████| 295/295 [00:02<00:00, 103.11it/s]

MAE (val set): 29.9616
MAE (test set): 29.8632
(val) -38.9371 (test) -38.7868

Epoch 46: 100%|██████████| 295/295 [00:03<00:00, 90.59it/s]

MAE (val set): 29.4323
MAE (test set): 29.3605
(val) -38.5754 (test) -38.4183
🌸 New best epoch! 🌸

Epoch 47: 100%|██████████| 295/295 [00:02<00:00, 114.58it/s]

MAE (val set): 29.6134
MAE (test set): 29.5350
(val) -38.7471 (test) -38.6059

Epoch 48: 100%|██████████| 295/295 [00:03<00:00, 86.25it/s]

MAE (val set): 29.6996
MAE (test set): 29.6198
(val) -38.6724 (test) -38.5381

Epoch 49: 100%|██████████| 295/295 [00:02<00:00, 103.02it/s]

MAE (val set): 29.5724
MAE (test set): 29.4618
(val) -38.5306 (test) -38.4177
🌸 New best epoch! 🌸

Epoch 50: 100%|██████████| 295/295 [00:03<00:00, 97.69it/s]

MAE (val set): 29.7498
MAE (test set): 29.6363
(val) -38.8679 (test) -38.6817

Epoch 51: 100%|██████████| 295/295 [00:03<00:00, 97.69it/s]

MAE (val set): 29.4641
MAE (test set): 29.3694
(val) -38.5682 (test) -38.4344

Epoch 52: 100%|██████████| 295/295 [00:03<00:00, 85.40it/s]

MAE (val set): 29.8176
MAE (test set): 29.7551
(val) -38.8471 (test) -38.7108

Epoch 53: 100%|██████████| 295/295 [00:02<00:00, 102.00it/s]

MAE (val set): 29.5574
MAE (test set): 29.4436
(val) -38.6854 (test) -38.4894

Epoch 54: 100%|██████████| 295/295 [00:03<00:00, 87.61it/s]

MAE (val set): 29.7899
MAE (test set): 29.7944
(val) -38.8160 (test) -38.7191

Epoch 55: 100%|██████████| 295/295 [00:02<00:00, 99.92it/s]

MAE (val set): 29.7350
MAE (test set): 29.6360
(val) -38.6047 (test) -38.4786

Epoch 56: 100%|██████████| 295/295 [00:03<00:00, 74.08it/s]

MAE (val set): 29.9105
MAE (test set): 29.9196
(val) -38.7464 (test) -38.7101

Epoch 57: 100%|██████████| 295/295 [00:03<00:00, 94.97it/s]

MAE (val set): 29.8908
MAE (test set): 29.8486
(val) -38.8606 (test) -38.7298

Epoch 58: 100%|██████████| 295/295 [00:02<00:00, 99.73it/s]

MAE (val set): 29.3825
MAE (test set): 29.3184
(val) -38.4129 (test) -38.3271
🌸 New best epoch! 🌸

Epoch 59: 100%|██████████| 295/295 [00:03<00:00, 85.70it/s]

MAE (val set): 29.6334
MAE (test set): 29.6073
(val) -38.5822 (test) -38.4920

Epoch 60: 100%|██████████| 295/295 [00:02<00:00, 107.58it/s]

MAE (val set): 29.7987
MAE (test set): 29.7394
(val) -38.7910 (test) -38.6710

Epoch 61: 100%|██████████| 295/295 [00:02<00:00, 102.10it/s]

MAE (val set): 29.4586
MAE (test set): 29.3598
(val) -38.4466 (test) -38.3221

Epoch 62: 100%|██████████| 295/295 [00:02<00:00, 100.94it/s]

MAE (val set): 29.6005
MAE (test set): 29.5863
(val) -38.5759 (test) -38.4680

Epoch 63: 100%|██████████| 295/295 [00:02<00:00, 105.17it/s]

MAE (val set): 29.4706
MAE (test set): 29.3938
(val) -38.3906 (test) -38.3295
🌸 New best epoch! 🌸

Epoch 64: 100%|██████████| 295/295 [00:02<00:00, 101.79it/s]

MAE (val set): 29.6721
MAE (test set): 29.5734
(val) -38.7143 (test) -38.5516

Epoch 65: 100%|██████████| 295/295 [00:02<00:00, 106.34it/s]

MAE (val set): 29.5239
MAE (test set): 29.4908
(val) -38.4426 (test) -38.3695

Epoch 66: 100%|██████████| 295/295 [00:03<00:00, 87.99it/s]

MAE (val set): 29.5029
MAE (test set): 29.4055
(val) -38.5268 (test) -38.3517

Epoch 67: 100%|██████████| 295/295 [00:02<00:00, 115.60it/s]

MAE (val set): 29.4935
MAE (test set): 29.4113
(val) -38.5868 (test) -38.4770

Epoch 68: 100%|██████████| 295/295 [00:03<00:00, 88.19it/s]

MAE (val set): 29.3680
MAE (test set): 29.2564
(val) -38.4592 (test) -38.3515

Epoch 69: 100%|██████████| 295/295 [00:02<00:00, 101.53it/s]

MAE (val set): 29.6466
MAE (test set): 29.6435
(val) -38.7511 (test) -38.6602

Epoch 70: 100%|██████████| 295/295 [00:03<00:00, 90.40it/s]

MAE (val set): 29.8335
MAE (test set): 29.7970
(val) -38.9618 (test) -38.8052

Epoch 71: 100%|██████████| 295/295 [00:03<00:00, 98.28it/s]

MAE (val set): 29.4056
MAE (test set): 29.3417
(val) -38.4943 (test) -38.4083

Epoch 72: 100%|██████████| 295/295 [00:04<00:00, 69.68it/s]

MAE (val set): 29.9004
MAE (test set): 29.9180
(val) -38.8741 (test) -38.8060

Epoch 73: 100%|██████████| 295/295 [00:02<00:00, 110.92it/s]

MAE (val set): 29.3821
MAE (test set): 29.3890
(val) -38.4592 (test) -38.3923

Epoch 74: 100%|██████████| 295/295 [00:03<00:00, 91.88it/s]

MAE (val set): 29.5140
MAE (test set): 29.5205
(val) -38.4882 (test) -38.4220

Epoch 75: 100%|██████████| 295/295 [00:02<00:00, 103.41it/s]

MAE (val set): 29.3433
MAE (test set): 29.2240
(val) -38.5331 (test) -38.3925

Epoch 76: 100%|██████████| 295/295 [00:02<00:00, 102.88it/s]

MAE (val set): 29.5793
MAE (test set): 29.5063
(val) -38.6272 (test) -38.4618

Epoch 77: 100%|██████████| 295/295 [00:03<00:00, 97.51it/s]

MAE (val set): 29.2969
MAE (test set): 29.1916
(val) -38.4167 (test) -38.2811

Epoch 78: 100%|██████████| 295/295 [00:02<00:00, 101.09it/s]

MAE (val set): 29.6335
MAE (test set): 29.5816
(val) -38.5560 (test) -38.4735

Epoch 79: 100%|██████████| 295/295 [00:03<00:00, 89.74it/s]

MAE (val set): 29.4518
MAE (test set): 29.3446
(val) -38.5001 (test) -38.3605

Epoch 80: 100%|██████████| 295/295 [00:02<00:00, 135.01it/s]

MAE (val set): 29.5776
MAE (test set): 29.5541
(val) -38.6487 (test) -38.5216


Result:
{'val': -38.39060592185118, 'test': -38.329470586347625, 'epoch': 63}

In [30]:
print('\n\nResult:')
print(best)

Result:
{'val': -38.39060592185118, 'test': -38.329470586347625, 'epoch': 63}

In [32]:
df_mf = pd.read_csv('molformer-emb.csv')
df_mf

,0,1,2,3,4,5,6,7,8,9,...,759,760,761,762,763,764,765,766,767,MP
0,0.232754,0.039662,0.603345,0.434351,-0.235619,-0.008117,-0.240256,-0.327148,-0.622383,-0.242045,...,0.511787,0.017956,-0.102726,0.593849,-0.322905,-2.748505,0.264649,-0.493542,0.170734,355.15
1,-0.035469,0.244099,0.824150,0.871007,0.381988,0.018918,-0.171494,-0.681534,0.314292,0.073357,...,-0.444052,-0.211882,-0.301885,-0.089473,-0.258444,-2.224507,0.016750,-0.915583,0.149851,373.65
2,-0.014357,0.257718,0.659238,0.541999,0.342051,0.048318,0.188520,-0.241498,-0.025705,-0.207805,...,-0.124264,0.174638,-0.048913,-0.015672,-0.385274,-2.904102,0.212661,-0.588502,-0.315535,373.75
3,0.392396,0.213285,0.820162,0.444167,-0.283028,-0.213827,0.098154,-0.381828,0.016981,-0.291995,...,-0.253576,-0.132808,0.243490,0.575032,0.081913,-2.777802,0.065183,-0.286023,-0.647094,373.70
4,0.630157,0.129021,0.930085,0.348113,-0.079924,-0.057398,0.470295,0.097515,-0.180795,-0.171304,...,0.135372,-0.524551,0.513307,-0.236967,-0.219924,-3.077367,0.617281,-0.337038,-0.176350,374.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117747,0.536852,0.122638,0.304402,-0.319562,-0.675866,0.010863,-0.525479,-0.008692,-0.520580,-0.474743,...,-0.322050,-0.702077,0.462894,0.641812,-0.209804,-2.338952,0.601882,-0.391491,-0.380140,395.65
117748,-0.091166,0.245632,-0.179062,0.299272,-0.800757,-0.122798,-0.938942,-0.098464,0.014622,-0.054302,...,-0.299069,0.062411,0.707462,0.116971,-0.379527,-2.399415,0.433567,-0.402556,-0.216447,396.15
117749,0.463926,0.466987,0.087009,0.034810,-1.054933,-0.277966,-0.886445,-0.060067,-0.231398,0.083403,...,0.006923,-0.156032,0.417531,0.423048,-0.546653,-2.341095,0.170920,-0.561870,-0.619896,327.65
117750,0.502144,0.065869,0.162445,-0.160113,-1.070973,-0.249068,-0.573376,-0.082146,0.197232,-0.234873,...,-0.269982,-0.340257,0.310560,0.339327,-0.547660,-2.511800,0.631499,-0.330420,-0.576203,488.15
117751,-0.164626,0.498604,-0.480907,0.286132,-0.866054,-0.548921,-0.711837,0.196849,0.095999,-0.226699,...,-0.135179,-0.376027,0.247147,0.514326,-0.289037,-1.974172,0.163462,-0.636052,-0.142280,389.15

In [33]:
# >>> Dataset.
TaskType = Literal['regression', 'binclass', 'multiclass']

# Regression.
task_type: TaskType = 'regression'
n_classes = None
dataset = df_mf
X_cont: np.ndarray = df_mf.iloc[:, :-1].to_numpy()
Y: np.ndarray = df_mf.iloc[:, -1].to_numpy()

task_is_regression = task_type == 'regression'

# >>> Continuous features.
X_cont: np.ndarray = X_cont.astype(np.float32)
n_cont_features = X_cont.shape[1]

# >>> Labels.
if task_type == 'regression':
    Y = Y.astype(np.float32)
else:
    assert n_classes is not None
    Y = Y.astype(np.int64)
    assert set(Y.tolist()) == set(
        range(n_classes)
    ), 'Classification labels must form the range [0, 1, ..., n_classes - 1]'

# >>> Split the dataset.
all_idx = np.arange(len(Y))
trainval_idx, test_idx = sklearn.model_selection.train_test_split(
    all_idx, train_size=0.8
)
train_idx, val_idx = sklearn.model_selection.train_test_split(
    trainval_idx, train_size=0.8
)
data_numpy = {
    'train': {'x_cont': X_cont[train_idx], 'y': Y[train_idx]},
    'val': {'x_cont': X_cont[val_idx], 'y': Y[val_idx]},
    'test': {'x_cont': X_cont[test_idx], 'y': Y[test_idx]},
}

X_cont_train_numpy = data_numpy['train']['x_cont']
noise = (
    np.random.default_rng(0)
    .normal(0.0, 1e-5, X_cont_train_numpy.shape)
    .astype(X_cont_train_numpy.dtype)
)
preprocessing = sklearn.preprocessing.QuantileTransformer(
    n_quantiles=max(min(len(train_idx) // 30, 1000), 10),
    output_distribution='normal',
    subsample=10**9,
).fit(X_cont_train_numpy + noise)
del X_cont_train_numpy

# Apply the preprocessing.
for part in data_numpy:
    data_numpy[part]['x_cont'] = preprocessing.transform(data_numpy[part]['x_cont'])


# Label preprocessing.
class RegressionLabelStats(NamedTuple):
    mean: float
    std: float


Y_train = data_numpy['train']['y'].copy()
if task_type == 'regression':
    # For regression tasks, it is highly recommended to standardize the training labels.
    regression_label_stats = RegressionLabelStats(
        Y_train.mean().item(), Y_train.std().item()
    )
    Y_train = (Y_train - regression_label_stats.mean) / regression_label_stats.std
else:
    regression_label_stats = None

data = {
    part: {k: torch.as_tensor(v, device=device) for k, v in data_numpy[part].items()}
    for part in data_numpy
}

Y_train = torch.as_tensor(Y_train, device=device)
if task_type == 'regression':
    for part in data:
        data[part]['y'] = data[part]['y'].float()
    Y_train = Y_train.float()
    
amp_dtype = (
    torch.bfloat16
    if torch.cuda.is_available() and torch.cuda.is_bf16_supported()
    else torch.float16
    if torch.cuda.is_available()
    else None
)
# Changing False to True will result in faster training on compatible hardware.
amp_enabled = False and amp_dtype is not None
grad_scaler = torch.cuda.amp.GradScaler() if amp_dtype is torch.float16 else None  # type: ignore

# torch.compile
compile_model = False

# fmt: off
print(
    f'Device:        {device.type.upper()}'
    f'\nAMP:           {amp_enabled} (dtype: {amp_dtype})'
    f'\ntorch.compile: {compile_model}'
)
# fmt: on

Device:        CUDA
AMP:           False (dtype: torch.bfloat16)
torch.compile: False

In [34]:
# Choose one of the two configurations below.

# TabM
arch_type = 'tabm'
bins = None

model = Model(
    n_num_features=n_cont_features,
    cat_cardinalities=[], # zero categorical data
    n_classes=n_classes,
    backbone={
        'type': 'MLP',
        'n_blocks': 3 if bins is None else 2,
        'd_block': 512,
        'dropout': 0.1,
    },
    bins=bins,
    num_embeddings=(
        None
        if bins is None
        else {
            'type': 'PiecewiseLinearEmbeddings',
            'd_embedding': 16,
            'activation': False,
            'version': 'B',
        }
    ),
    arch_type=arch_type,
    k=32,
    share_training_batches=True,
).to(device)
optimizer = torch.optim.AdamW(make_parameter_groups(model), lr=2e-3, weight_decay=3e-4)

if compile_model:
    # NOTE
    # `torch.compile` is intentionally called without the `mode` argument
    # (mode="reduce-overhead" caused issues during training with torch==2.0.1).
    model = torch.compile(model)
    evaluation_mode = torch.no_grad
else:
    evaluation_mode = torch.inference_mode
    
@torch.autocast(device.type, enabled=amp_enabled, dtype=amp_dtype)  # type: ignore[code]
def apply_model(part: str, idx: Tensor) -> Tensor:
    return (
        model(
            data[part]['x_cont'][idx],
            data[part]['x_cat'][idx] if 'x_cat' in data[part] else None,
        )
        .squeeze(-1)  # Remove the last dimension for regression tasks.
        .float()
    )


base_loss_fn = F.mse_loss if task_type == 'regression' else F.cross_entropy


def loss_fn(y_pred: Tensor, y_true: Tensor) -> Tensor:
    # TabM produces k predictions. Each of them must be trained separately.
    # (regression)     y_pred.shape == (batch_size, k)
    # (classification) y_pred.shape == (batch_size, k, n_classes)
    k = y_pred.shape[-1 if task_type == 'regression' else -2]
    return base_loss_fn(
        y_pred.flatten(0, 1),
        y_true.repeat_interleave(k) if model.share_training_batches else y_true,
    )


@evaluation_mode()
def evaluate(part: str) -> float:
    model.eval()

    # When using torch.compile, you may need to reduce the evaluation batch size.
    eval_batch_size = 8096
    y_pred: np.ndarray = (
        torch.cat(
            [
                apply_model(part, idx)
                for idx in torch.arange(len(data[part]['y']), device=device).split(
                    eval_batch_size
                )
            ]
        )
        .cpu()
        .numpy()
    )
    if task_type == 'regression':
        # Transform the predictions back to the original label space.
        assert regression_label_stats is not None
        y_pred = y_pred * regression_label_stats.std + regression_label_stats.mean

    # Compute the mean of the k predictions.
    if task_type != 'regression':
        # For classification, the mean must be computed in the probabily space.
        y_pred = scipy.special.softmax(y_pred, axis=-1)
    y_pred = y_pred.mean(1)

    y_true = data[part]['y'].cpu().numpy()
    mae = sklearn.metrics.mean_absolute_error(y_true, y_pred)
    print(f'MAE ({part} set): {mae:.4f}')  # [ADDED MAE PRINT]
    score = (
        -(sklearn.metrics.mean_squared_error(y_true, y_pred) ** 0.5)
        if task_type == 'regression'
        else sklearn.metrics.accuracy_score(y_true, y_pred.argmax(1))
    )
    return float(score)  # The higher -- the better.


print(f'Test score before training: {evaluate("test"):.4f}')

MAE (test set): 56.2370
Test score before training: -71.5915

In [35]:
%time
n_epochs = 1_000_000_000
patience = 16

train_size = len(train_idx)
batch_size = 256
epoch_size = math.ceil(train_size / batch_size)
best = {
    'val': -math.inf,
    'test': -math.inf,
    'epoch': -1,
}
# Early stopping: the training stops when
# there are more than `patience` consequtive bad updates.
patience = 16
remaining_patience = patience

print('-' * 88 + '\n')
for epoch in range(n_epochs):
    batches = (
        torch.randperm(train_size, device=device).split(batch_size)
        if model.share_training_batches
        else [
            x.transpose(0, 1).flatten()
            for x in torch.rand((model.k, train_size), device=device)
            .argsort(dim=1)
            .split(batch_size, dim=1)
        ]
    )
    for batch_idx in tqdm(batches, desc=f'Epoch {epoch}'):
        model.train()
        optimizer.zero_grad()
        loss = loss_fn(apply_model('train', batch_idx), Y_train[batch_idx])
        if grad_scaler is None:
            loss.backward()
            optimizer.step()
        else:
            grad_scaler.scale(loss).backward()  # type: ignore
            grad_scaler.step(optimizer)
            grad_scaler.update()

    val_score = evaluate('val')
    test_score = evaluate('test')
    print(f'(val) {val_score:.4f} (test) {test_score:.4f}')

    if val_score > best['val']:
        print('🌸 New best epoch! 🌸')
        best = {'val': val_score, 'test': test_score, 'epoch': epoch}
        remaining_patience = patience
    else:
        remaining_patience -= 1

    if remaining_patience < 0:
        break

    print()

print('\n\nResult:')
print(best)

CPU times: user 31 µs, sys: 0 ns, total: 31 µs
Wall time: 64.4 µs
----------------------------------------------------------------------------------------

Epoch 0: 100%|██████████| 295/295 [00:03<00:00, 82.15it/s]

MAE (val set): 31.8265
MAE (test set): 32.3269
(val) -41.2789 (test) -41.8286
🌸 New best epoch! 🌸

Epoch 1: 100%|██████████| 295/295 [00:03<00:00, 91.49it/s]

MAE (val set): 30.4734
MAE (test set): 30.8124
(val) -40.1065 (test) -40.4765
🌸 New best epoch! 🌸

Epoch 2: 100%|██████████| 295/295 [00:03<00:00, 93.23it/s]

MAE (val set): 30.8446
MAE (test set): 31.3717
(val) -40.0576 (test) -40.5601
🌸 New best epoch! 🌸

Epoch 3: 100%|██████████| 295/295 [00:03<00:00, 78.75it/s]

MAE (val set): 29.9512
MAE (test set): 30.3620
(val) -39.1633 (test) -39.5930
🌸 New best epoch! 🌸

Epoch 4: 100%|██████████| 295/295 [00:02<00:00, 103.04it/s]

MAE (val set): 29.8400
MAE (test set): 30.2623
(val) -38.9644 (test) -39.3670
🌸 New best epoch! 🌸

Epoch 5: 100%|██████████| 295/295 [00:03<00:00, 92.61it/s]

MAE (val set): 30.8087
MAE (test set): 31.4378
(val) -39.9015 (test) -40.4998

Epoch 6: 100%|██████████| 295/295 [00:03<00:00, 97.11it/s]

MAE (val set): 29.7131
MAE (test set): 30.2963
(val) -38.8579 (test) -39.4677
🌸 New best epoch! 🌸

Epoch 7: 100%|██████████| 295/295 [00:03<00:00, 89.03it/s]

MAE (val set): 29.4647
MAE (test set): 30.0582
(val) -38.8221 (test) -39.4492
🌸 New best epoch! 🌸

Epoch 8: 100%|██████████| 295/295 [00:03<00:00, 93.52it/s]

MAE (val set): 29.2615
MAE (test set): 29.7040
(val) -38.3370 (test) -38.7567
🌸 New best epoch! 🌸

Epoch 9: 100%|██████████| 295/295 [00:03<00:00, 90.22it/s]

MAE (val set): 28.9079
MAE (test set): 29.3054
(val) -38.0223 (test) -38.4842
🌸 New best epoch! 🌸

Epoch 10: 100%|██████████| 295/295 [00:03<00:00, 83.19it/s]

MAE (val set): 29.0035
MAE (test set): 29.3533
(val) -38.0610 (test) -38.4427

Epoch 11: 100%|██████████| 295/295 [00:02<00:00, 98.95it/s]

MAE (val set): 28.7065
MAE (test set): 29.1447
(val) -37.8844 (test) -38.3524
🌸 New best epoch! 🌸

Epoch 12: 100%|██████████| 295/295 [00:03<00:00, 93.91it/s]

MAE (val set): 28.7862
MAE (test set): 29.2349
(val) -38.1123 (test) -38.5527

Epoch 13: 100%|██████████| 295/295 [00:03<00:00, 91.79it/s]

MAE (val set): 28.6469
MAE (test set): 29.0996
(val) -37.6962 (test) -38.1724
🌸 New best epoch! 🌸

Epoch 14: 100%|██████████| 295/295 [00:02<00:00, 115.85it/s]

MAE (val set): 28.5676
MAE (test set): 28.8702
(val) -37.6964 (test) -38.0363

Epoch 15: 100%|██████████| 295/295 [00:03<00:00, 95.12it/s]

MAE (val set): 28.8198
MAE (test set): 29.3255
(val) -37.8212 (test) -38.3190

Epoch 16: 100%|██████████| 295/295 [00:03<00:00, 90.66it/s]

MAE (val set): 28.5326
MAE (test set): 28.9198
(val) -37.5735 (test) -38.0051
🌸 New best epoch! 🌸

Epoch 17: 100%|██████████| 295/295 [00:02<00:00, 112.50it/s]

MAE (val set): 28.8574
MAE (test set): 29.2381
(val) -37.7422 (test) -38.1453

Epoch 18: 100%|██████████| 295/295 [00:03<00:00, 90.15it/s]

MAE (val set): 28.6571
MAE (test set): 29.1240
(val) -37.5635 (test) -38.0943
🌸 New best epoch! 🌸

Epoch 19: 100%|██████████| 295/295 [00:03<00:00, 96.95it/s]

MAE (val set): 28.5439
MAE (test set): 28.9046
(val) -37.4755 (test) -37.8584
🌸 New best epoch! 🌸

Epoch 20: 100%|██████████| 295/295 [00:03<00:00, 95.19it/s]

MAE (val set): 28.9597
MAE (test set): 29.4517
(val) -37.9043 (test) -38.4786

Epoch 21: 100%|██████████| 295/295 [00:03<00:00, 86.34it/s]

MAE (val set): 28.5638
MAE (test set): 28.9921
(val) -37.4412 (test) -37.9200
🌸 New best epoch! 🌸

Epoch 22: 100%|██████████| 295/295 [00:02<00:00, 100.09it/s]

MAE (val set): 28.1924
MAE (test set): 28.6114
(val) -37.2613 (test) -37.7397
🌸 New best epoch! 🌸

Epoch 23: 100%|██████████| 295/295 [00:03<00:00, 86.57it/s]

MAE (val set): 28.0728
MAE (test set): 28.4759
(val) -37.2416 (test) -37.6750
🌸 New best epoch! 🌸

Epoch 24: 100%|██████████| 295/295 [00:03<00:00, 95.79it/s]

MAE (val set): 28.6125
MAE (test set): 29.0646
(val) -37.6769 (test) -38.2620

Epoch 25: 100%|██████████| 295/295 [00:02<00:00, 98.49it/s]

MAE (val set): 28.4459
MAE (test set): 28.8556
(val) -37.4235 (test) -37.9350

Epoch 26: 100%|██████████| 295/295 [00:03<00:00, 81.45it/s]

MAE (val set): 28.4068
MAE (test set): 28.8411
(val) -37.2306 (test) -37.7391
🌸 New best epoch! 🌸

Epoch 27: 100%|██████████| 295/295 [00:02<00:00, 104.84it/s]

MAE (val set): 28.5877
MAE (test set): 29.0081
(val) -37.3747 (test) -37.8515

Epoch 28: 100%|██████████| 295/295 [00:03<00:00, 91.17it/s]

MAE (val set): 28.4297
MAE (test set): 28.8929
(val) -37.2938 (test) -37.8178

Epoch 29: 100%|██████████| 295/295 [00:03<00:00, 94.92it/s]

MAE (val set): 28.3797
MAE (test set): 28.7810
(val) -37.2196 (test) -37.6971
🌸 New best epoch! 🌸

Epoch 30: 100%|██████████| 295/295 [00:03<00:00, 91.63it/s]

MAE (val set): 28.4406
MAE (test set): 28.8375
(val) -37.2756 (test) -37.6958

Epoch 31: 100%|██████████| 295/295 [00:03<00:00, 82.89it/s]

MAE (val set): 28.3165
MAE (test set): 28.7790
(val) -37.2956 (test) -37.7986

Epoch 32: 100%|██████████| 295/295 [00:02<00:00, 113.32it/s]

MAE (val set): 28.6765
MAE (test set): 29.1153
(val) -37.4356 (test) -37.9402

Epoch 33: 100%|██████████| 295/295 [00:03<00:00, 80.44it/s]

MAE (val set): 28.2047
MAE (test set): 28.6251
(val) -37.1999 (test) -37.6476
🌸 New best epoch! 🌸

Epoch 34: 100%|██████████| 295/295 [00:02<00:00, 100.15it/s]

MAE (val set): 28.4983
MAE (test set): 28.9440
(val) -37.3795 (test) -37.8459

Epoch 35: 100%|██████████| 295/295 [00:03<00:00, 88.09it/s]

MAE (val set): 28.2132
MAE (test set): 28.5663
(val) -37.0757 (test) -37.4480
🌸 New best epoch! 🌸

Epoch 36: 100%|██████████| 295/295 [00:03<00:00, 96.26it/s]

MAE (val set): 28.4237
MAE (test set): 28.8754
(val) -37.2556 (test) -37.7836

Epoch 37: 100%|██████████| 295/295 [00:03<00:00, 83.24it/s]

MAE (val set): 27.9043
MAE (test set): 28.2970
(val) -36.8661 (test) -37.3379
🌸 New best epoch! 🌸

Epoch 38: 100%|██████████| 295/295 [00:03<00:00, 93.05it/s]

MAE (val set): 28.1044
MAE (test set): 28.5562
(val) -37.0454 (test) -37.5643

Epoch 39: 100%|██████████| 295/295 [00:03<00:00, 88.01it/s]

MAE (val set): 28.3308
MAE (test set): 28.8456
(val) -37.3330 (test) -37.9765

Epoch 40: 100%|██████████| 295/295 [00:03<00:00, 93.18it/s]

MAE (val set): 28.4109
MAE (test set): 28.8196
(val) -37.1430 (test) -37.6102

Epoch 41: 100%|██████████| 295/295 [00:03<00:00, 95.87it/s]

MAE (val set): 28.4260
MAE (test set): 28.9145
(val) -37.3326 (test) -37.9426

Epoch 42: 100%|██████████| 295/295 [00:03<00:00, 89.24it/s]

MAE (val set): 28.0734
MAE (test set): 28.5433
(val) -37.0435 (test) -37.5982

Epoch 43: 100%|██████████| 295/295 [00:03<00:00, 76.24it/s]

MAE (val set): 27.8804
MAE (test set): 28.3111
(val) -36.9303 (test) -37.4037

Epoch 44: 100%|██████████| 295/295 [00:03<00:00, 90.11it/s]

MAE (val set): 27.8187
MAE (test set): 28.1774
(val) -36.8192 (test) -37.2284
🌸 New best epoch! 🌸

Epoch 45: 100%|██████████| 295/295 [00:02<00:00, 104.46it/s]

MAE (val set): 28.1957
MAE (test set): 28.5913
(val) -37.0576 (test) -37.4712

Epoch 46: 100%|██████████| 295/295 [00:03<00:00, 96.24it/s]

MAE (val set): 28.0049
MAE (test set): 28.4457
(val) -37.0528 (test) -37.5570

Epoch 47: 100%|██████████| 295/295 [00:03<00:00, 88.81it/s]

MAE (val set): 27.9568
MAE (test set): 28.3781
(val) -36.9537 (test) -37.4041

Epoch 48: 100%|██████████| 295/295 [00:02<00:00, 98.62it/s]

MAE (val set): 28.1197
MAE (test set): 28.5155
(val) -36.9228 (test) -37.3683

Epoch 49: 100%|██████████| 295/295 [00:02<00:00, 99.07it/s]

MAE (val set): 28.2347
MAE (test set): 28.7227
(val) -37.1642 (test) -37.7445

Epoch 50: 100%|██████████| 295/295 [00:03<00:00, 88.55it/s]

MAE (val set): 27.8322
MAE (test set): 28.2003
(val) -36.7211 (test) -37.1510
🌸 New best epoch! 🌸

Epoch 51: 100%|██████████| 295/295 [00:03<00:00, 97.50it/s]

MAE (val set): 27.9676
MAE (test set): 28.4035
(val) -36.8704 (test) -37.3684

Epoch 52: 100%|██████████| 295/295 [00:02<00:00, 103.39it/s]

MAE (val set): 28.0328
MAE (test set): 28.3980
(val) -36.8778 (test) -37.3151

Epoch 53: 100%|██████████| 295/295 [00:03<00:00, 84.33it/s]

MAE (val set): 27.8866
MAE (test set): 28.2971
(val) -36.7991 (test) -37.2932

Epoch 54: 100%|██████████| 295/295 [00:02<00:00, 99.73it/s]

MAE (val set): 27.8095
MAE (test set): 28.2274
(val) -36.8230 (test) -37.2658

Epoch 55: 100%|██████████| 295/295 [00:03<00:00, 95.71it/s]

MAE (val set): 28.1385
MAE (test set): 28.5354
(val) -37.0465 (test) -37.5416

Epoch 56: 100%|██████████| 295/295 [00:03<00:00, 94.03it/s]

MAE (val set): 27.7382
MAE (test set): 28.0787
(val) -36.6809 (test) -37.0726
🌸 New best epoch! 🌸

Epoch 57: 100%|██████████| 295/295 [00:02<00:00, 107.41it/s]

MAE (val set): 27.8831
MAE (test set): 28.2675
(val) -36.8039 (test) -37.2500

Epoch 58: 100%|██████████| 295/295 [00:03<00:00, 84.45it/s]

MAE (val set): 27.8782
MAE (test set): 28.2635
(val) -36.7496 (test) -37.2114

Epoch 59: 100%|██████████| 295/295 [00:02<00:00, 102.32it/s]

MAE (val set): 27.9355
MAE (test set): 28.3733
(val) -36.7888 (test) -37.3099

Epoch 60: 100%|██████████| 295/295 [00:03<00:00, 93.53it/s]

MAE (val set): 28.0229
MAE (test set): 28.4029
(val) -36.8318 (test) -37.2745

Epoch 61: 100%|██████████| 295/295 [00:03<00:00, 97.31it/s]

MAE (val set): 28.0420
MAE (test set): 28.4259
(val) -36.9075 (test) -37.3283

Epoch 62: 100%|██████████| 295/295 [00:03<00:00, 95.66it/s]

MAE (val set): 27.7010
MAE (test set): 28.0858
(val) -36.7583 (test) -37.1948

Epoch 63: 100%|██████████| 295/295 [00:03<00:00, 82.90it/s]

MAE (val set): 27.9354
MAE (test set): 28.2881
(val) -36.7869 (test) -37.1958

Epoch 64: 100%|██████████| 295/295 [00:02<00:00, 115.96it/s]

MAE (val set): 27.9937
MAE (test set): 28.4111
(val) -36.8290 (test) -37.2766

Epoch 65: 100%|██████████| 295/295 [00:03<00:00, 81.49it/s]

MAE (val set): 27.9285
MAE (test set): 28.3505
(val) -36.8367 (test) -37.3463

Epoch 66: 100%|██████████| 295/295 [00:03<00:00, 97.67it/s]

MAE (val set): 27.7835
MAE (test set): 28.1784
(val) -36.6841 (test) -37.1081

Epoch 67: 100%|██████████| 295/295 [00:03<00:00, 89.14it/s]

MAE (val set): 27.8508
MAE (test set): 28.2285
(val) -36.7453 (test) -37.1581

Epoch 68: 100%|██████████| 295/295 [00:03<00:00, 96.38it/s]

MAE (val set): 27.7981
MAE (test set): 28.1805
(val) -36.7521 (test) -37.1866

Epoch 69: 100%|██████████| 295/295 [00:03<00:00, 95.92it/s]

MAE (val set): 27.8955
MAE (test set): 28.2766
(val) -36.7418 (test) -37.1493

Epoch 70: 100%|██████████| 295/295 [00:03<00:00, 82.47it/s]

MAE (val set): 27.9108
MAE (test set): 28.3509
(val) -36.7754 (test) -37.2587

Epoch 71: 100%|██████████| 295/295 [00:02<00:00, 99.34it/s]

MAE (val set): 27.5786
MAE (test set): 27.9602
(val) -36.5992 (test) -37.0038
🌸 New best epoch! 🌸

Epoch 72: 100%|██████████| 295/295 [00:03<00:00, 91.51it/s]

MAE (val set): 28.0399
MAE (test set): 28.4213
(val) -36.8158 (test) -37.2232

Epoch 73: 100%|██████████| 295/295 [00:03<00:00, 94.41it/s]

MAE (val set): 27.7016
MAE (test set): 28.1254
(val) -36.6693 (test) -37.1256

Epoch 74: 100%|██████████| 295/295 [00:04<00:00, 71.61it/s]

MAE (val set): 27.7944
MAE (test set): 28.2152
(val) -36.7108 (test) -37.1498

Epoch 75: 100%|██████████| 295/295 [00:02<00:00, 107.24it/s]

MAE (val set): 27.9045
MAE (test set): 28.3070
(val) -36.7746 (test) -37.2234

Epoch 76: 100%|██████████| 295/295 [00:02<00:00, 100.33it/s]

MAE (val set): 27.8516
MAE (test set): 28.2831
(val) -36.7395 (test) -37.2244

Epoch 77: 100%|██████████| 295/295 [00:03<00:00, 97.00it/s]

MAE (val set): 27.6927
MAE (test set): 28.0235
(val) -36.7073 (test) -37.0754

Epoch 78: 100%|██████████| 295/295 [00:02<00:00, 102.95it/s]

MAE (val set): 27.9225
MAE (test set): 28.3458
(val) -36.7821 (test) -37.2550

Epoch 79: 100%|██████████| 295/295 [00:03<00:00, 94.39it/s]

MAE (val set): 27.6963
MAE (test set): 28.0708
(val) -36.5925 (test) -36.9960
🌸 New best epoch! 🌸

Epoch 80: 100%|██████████| 295/295 [00:02<00:00, 114.45it/s]

MAE (val set): 27.6348
MAE (test set): 28.0462
(val) -36.6173 (test) -37.0953

Epoch 81: 100%|██████████| 295/295 [00:03<00:00, 88.90it/s]

MAE (val set): 27.7842
MAE (test set): 28.1526
(val) -36.7165 (test) -37.1332

Epoch 82: 100%|██████████| 295/295 [00:02<00:00, 99.90it/s]

MAE (val set): 27.8822
MAE (test set): 28.3083
(val) -36.7064 (test) -37.1936

Epoch 83: 100%|██████████| 295/295 [00:02<00:00, 101.18it/s]

MAE (val set): 27.7489
MAE (test set): 28.1455
(val) -36.6141 (test) -37.0669

Epoch 84: 100%|██████████| 295/295 [00:03<00:00, 98.18it/s]

MAE (val set): 27.7595
MAE (test set): 28.2029
(val) -36.6514 (test) -37.1764

Epoch 85: 100%|██████████| 295/295 [00:02<00:00, 108.80it/s]

MAE (val set): 27.8868
MAE (test set): 28.3504
(val) -36.8023 (test) -37.3343

Epoch 86: 100%|██████████| 295/295 [00:03<00:00, 88.30it/s]

MAE (val set): 27.6797
MAE (test set): 28.0727
(val) -36.6334 (test) -37.0604

Epoch 87: 100%|██████████| 295/295 [00:02<00:00, 121.23it/s]

MAE (val set): 27.9150
MAE (test set): 28.3270
(val) -36.7561 (test) -37.1883

Epoch 88: 100%|██████████| 295/295 [00:03<00:00, 91.73it/s]

MAE (val set): 27.7115
MAE (test set): 28.1579
(val) -36.6310 (test) -37.1305

Epoch 89: 100%|██████████| 295/295 [00:02<00:00, 102.81it/s]

MAE (val set): 27.6993
MAE (test set): 28.0588
(val) -36.5752 (test) -36.9581
🌸 New best epoch! 🌸

Epoch 90: 100%|██████████| 295/295 [00:03<00:00, 98.10it/s]

MAE (val set): 27.7852
MAE (test set): 28.2174
(val) -36.6365 (test) -37.1376

Epoch 91: 100%|██████████| 295/295 [00:02<00:00, 100.68it/s]

MAE (val set): 27.7065
MAE (test set): 28.1196
(val) -36.6440 (test) -37.0595

Epoch 92: 100%|██████████| 295/295 [00:02<00:00, 101.95it/s]

MAE (val set): 27.6150
MAE (test set): 28.0157
(val) -36.5674 (test) -37.0530
🌸 New best epoch! 🌸

Epoch 93: 100%|██████████| 295/295 [00:03<00:00, 87.54it/s]

MAE (val set): 27.7737
MAE (test set): 28.1698
(val) -36.7036 (test) -37.1238

Epoch 94: 100%|██████████| 295/295 [00:02<00:00, 115.39it/s]

MAE (val set): 27.9882
MAE (test set): 28.4375
(val) -36.8149 (test) -37.3179

Epoch 95: 100%|██████████| 295/295 [00:03<00:00, 84.35it/s]

MAE (val set): 27.6559
MAE (test set): 28.0888
(val) -36.5895 (test) -37.0575

Epoch 96: 100%|██████████| 295/295 [00:02<00:00, 101.27it/s]

MAE (val set): 27.7380
MAE (test set): 28.1702
(val) -36.6373 (test) -37.1274

Epoch 97: 100%|██████████| 295/295 [00:03<00:00, 92.06it/s]

MAE (val set): 27.6852
MAE (test set): 28.0973
(val) -36.5874 (test) -37.0379

Epoch 98: 100%|██████████| 295/295 [00:03<00:00, 98.07it/s]

MAE (val set): 27.5364
MAE (test set): 27.8750
(val) -36.5144 (test) -36.9134
🌸 New best epoch! 🌸

Epoch 99: 100%|██████████| 295/295 [00:03<00:00, 94.56it/s]

MAE (val set): 27.7577
MAE (test set): 28.1265
(val) -36.6618 (test) -37.1062

Epoch 100: 100%|██████████| 295/295 [00:03<00:00, 84.75it/s]

MAE (val set): 27.8960
MAE (test set): 28.2826
(val) -36.7238 (test) -37.1607

Epoch 101: 100%|██████████| 295/295 [00:03<00:00, 97.28it/s]

MAE (val set): 27.6491
MAE (test set): 28.0548
(val) -36.5919 (test) -37.0266

Epoch 102: 100%|██████████| 295/295 [00:03<00:00, 91.17it/s]

MAE (val set): 27.5081
MAE (test set): 27.8977
(val) -36.5000 (test) -36.9078
🌸 New best epoch! 🌸

Epoch 103: 100%|██████████| 295/295 [00:03<00:00, 94.19it/s]

MAE (val set): 27.5977
MAE (test set): 28.0033
(val) -36.5556 (test) -36.9523

Epoch 104: 100%|██████████| 295/295 [00:03<00:00, 96.13it/s]

MAE (val set): 27.6791
MAE (test set): 28.1058
(val) -36.5947 (test) -37.1046

Epoch 105: 100%|██████████| 295/295 [00:03<00:00, 95.92it/s]

MAE (val set): 28.0299
MAE (test set): 28.4153
(val) -36.7808 (test) -37.1912

Epoch 106: 100%|██████████| 295/295 [00:03<00:00, 92.22it/s]

MAE (val set): 27.5973
MAE (test set): 27.9938
(val) -36.5422 (test) -36.9867

Epoch 107: 100%|██████████| 295/295 [00:03<00:00, 83.82it/s]

MAE (val set): 27.6780
MAE (test set): 28.0910
(val) -36.5583 (test) -37.0170

Epoch 108: 100%|██████████| 295/295 [00:02<00:00, 107.03it/s]

MAE (val set): 27.6402
MAE (test set): 28.0249
(val) -36.5684 (test) -36.9857

Epoch 109: 100%|██████████| 295/295 [00:03<00:00, 92.40it/s]

MAE (val set): 27.5291
MAE (test set): 27.9633
(val) -36.5062 (test) -36.9706

Epoch 110: 100%|██████████| 295/295 [00:02<00:00, 109.29it/s]

MAE (val set): 27.8281
MAE (test set): 28.2453
(val) -36.7048 (test) -37.1722

Epoch 111: 100%|██████████| 295/295 [00:02<00:00, 100.68it/s]

MAE (val set): 27.7455
MAE (test set): 28.1377
(val) -36.6215 (test) -37.0253

Epoch 112: 100%|██████████| 295/295 [00:03<00:00, 97.85it/s]

MAE (val set): 27.7877
MAE (test set): 28.1637
(val) -36.6690 (test) -37.0612

Epoch 113: 100%|██████████| 295/295 [00:02<00:00, 103.16it/s]

MAE (val set): 27.5859
MAE (test set): 27.9553
(val) -36.5226 (test) -36.9294

Epoch 114: 100%|██████████| 295/295 [00:03<00:00, 90.08it/s]

MAE (val set): 27.7677
MAE (test set): 28.1801
(val) -36.6015 (test) -37.0591

Epoch 115: 100%|██████████| 295/295 [00:02<00:00, 114.95it/s]

MAE (val set): 27.6957
MAE (test set): 28.0606
(val) -36.6188 (test) -37.0086

Epoch 116: 100%|██████████| 295/295 [00:03<00:00, 93.56it/s]

MAE (val set): 27.7603
MAE (test set): 28.1630
(val) -36.5824 (test) -37.0194

Epoch 117: 100%|██████████| 295/295 [00:02<00:00, 98.79it/s]

MAE (val set): 27.6404
MAE (test set): 28.0308
(val) -36.5453 (test) -36.9683

Epoch 118: 100%|██████████| 295/295 [00:03<00:00, 98.00it/s]

MAE (val set): 27.6329
MAE (test set): 28.0481
(val) -36.5746 (test) -36.9692

Epoch 119: 100%|██████████| 295/295 [00:03<00:00, 88.28it/s]

MAE (val set): 27.6063
MAE (test set): 27.9858
(val) -36.4892 (test) -36.8865
🌸 New best epoch! 🌸

Epoch 120: 100%|██████████| 295/295 [00:02<00:00, 116.17it/s]

MAE (val set): 27.5310
MAE (test set): 27.9710
(val) -36.5016 (test) -36.9601

Epoch 121: 100%|██████████| 295/295 [00:03<00:00, 86.92it/s]

MAE (val set): 27.6774
MAE (test set): 28.1109
(val) -36.5599 (test) -37.0314

Epoch 122: 100%|██████████| 295/295 [00:02<00:00, 100.65it/s]

MAE (val set): 27.7301
MAE (test set): 28.1585
(val) -36.6337 (test) -37.1099

Epoch 123: 100%|██████████| 295/295 [00:03<00:00, 95.91it/s]

MAE (val set): 27.7082
MAE (test set): 28.1430
(val) -36.5873 (test) -37.0927

Epoch 124: 100%|██████████| 295/295 [00:03<00:00, 94.90it/s]

MAE (val set): 27.7239
MAE (test set): 28.1506
(val) -36.6115 (test) -37.0952

Epoch 125: 100%|██████████| 295/295 [00:02<00:00, 106.98it/s]

MAE (val set): 27.7579
MAE (test set): 28.1418
(val) -36.5855 (test) -37.0162

Epoch 126: 100%|██████████| 295/295 [00:03<00:00, 82.60it/s]

MAE (val set): 27.6473
MAE (test set): 28.0339
(val) -36.5315 (test) -36.9504

Epoch 127: 100%|██████████| 295/295 [00:02<00:00, 110.49it/s]

MAE (val set): 27.5587
MAE (test set): 27.9637
(val) -36.4740 (test) -36.9147
🌸 New best epoch! 🌸

Epoch 128: 100%|██████████| 295/295 [00:03<00:00, 87.51it/s]

MAE (val set): 27.6473
MAE (test set): 28.1137
(val) -36.6076 (test) -37.1182

Epoch 129: 100%|██████████| 295/295 [00:03<00:00, 93.32it/s]

MAE (val set): 27.5610
MAE (test set): 27.9855
(val) -36.5230 (test) -36.9685

Epoch 130: 100%|██████████| 295/295 [00:03<00:00, 89.38it/s]

MAE (val set): 27.7213
MAE (test set): 28.1519
(val) -36.6336 (test) -37.1126

Epoch 131: 100%|██████████| 295/295 [00:03<00:00, 82.85it/s]

MAE (val set): 27.4317
MAE (test set): 27.8549
(val) -36.4418 (test) -36.8554
🌸 New best epoch! 🌸

Epoch 132: 100%|██████████| 295/295 [00:03<00:00, 98.22it/s]

MAE (val set): 27.7169
MAE (test set): 28.1269
(val) -36.5710 (test) -37.0266

Epoch 133: 100%|██████████| 295/295 [00:03<00:00, 92.32it/s]

MAE (val set): 27.6656
MAE (test set): 28.0902
(val) -36.5329 (test) -37.0114

Epoch 134: 100%|██████████| 295/295 [00:03<00:00, 96.17it/s]

MAE (val set): 27.5691
MAE (test set): 27.9151
(val) -36.5003 (test) -36.8610

Epoch 135: 100%|██████████| 295/295 [00:03<00:00, 98.13it/s]

MAE (val set): 27.7288
MAE (test set): 28.0964
(val) -36.6009 (test) -36.9612

Epoch 136: 100%|██████████| 295/295 [00:03<00:00, 93.38it/s]

MAE (val set): 27.6055
MAE (test set): 28.0074
(val) -36.5730 (test) -37.0177

Epoch 137: 100%|██████████| 295/295 [00:03<00:00, 94.81it/s]

MAE (val set): 27.8028
MAE (test set): 28.2307
(val) -36.6376 (test) -37.1222

Epoch 138: 100%|██████████| 295/295 [00:04<00:00, 72.90it/s]

MAE (val set): 27.4867
MAE (test set): 27.8679
(val) -36.5331 (test) -36.9430

Epoch 139: 100%|██████████| 295/295 [00:03<00:00, 87.34it/s]

MAE (val set): 27.6078
MAE (test set): 27.9937
(val) -36.4565 (test) -36.8956

Epoch 140: 100%|██████████| 295/295 [00:03<00:00, 93.11it/s]

MAE (val set): 27.5950
MAE (test set): 27.9804
(val) -36.5104 (test) -36.8715

Epoch 141: 100%|██████████| 295/295 [00:02<00:00, 108.69it/s]

MAE (val set): 27.6904
MAE (test set): 28.0367
(val) -36.5553 (test) -36.9278

Epoch 142: 100%|██████████| 295/295 [00:03<00:00, 98.08it/s]

MAE (val set): 27.5542
MAE (test set): 27.9289
(val) -36.4982 (test) -36.8805

Epoch 143: 100%|██████████| 295/295 [00:02<00:00, 99.33it/s]

MAE (val set): 27.6763
MAE (test set): 28.0654
(val) -36.5578 (test) -36.9632

Epoch 144: 100%|██████████| 295/295 [00:02<00:00, 103.55it/s]

MAE (val set): 27.6306
MAE (test set): 28.0135
(val) -36.5339 (test) -36.9691

Epoch 145: 100%|██████████| 295/295 [00:03<00:00, 89.05it/s]

MAE (val set): 27.7430
MAE (test set): 28.1048
(val) -36.6203 (test) -37.0103

Epoch 146: 100%|██████████| 295/295 [00:02<00:00, 106.28it/s]

MAE (val set): 27.6307
MAE (test set): 28.0061
(val) -36.5165 (test) -36.9406

Epoch 147: 100%|██████████| 295/295 [00:03<00:00, 88.56it/s]

MAE (val set): 27.5660
MAE (test set): 27.9449
(val) -36.5416 (test) -36.9478

Epoch 148: 100%|██████████| 295/295 [00:03<00:00, 93.19it/s]

MAE (val set): 27.6304
MAE (test set): 27.9688
(val) -36.5164 (test) -36.8982


Result:
{'val': -36.44182978402446, 'test': -36.85538077129139, 'epoch': 131}

In [37]:
print('\n\nResult:')
print(best)

Result:
{'val': -36.44182978402446, 'test': -36.85538077129139, 'epoch': 131}

In [46]:
df_mr = pd.read_csv('emb_morgan_df.csv')
df_mr

,0,1,2,3,4,5,6,7,8,9,...,4087,4088,4089,4090,4091,4092,4093,4094,4095,MP
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,355.15
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,373.65
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,373.75
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,373.70
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,374.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117747,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,395.65
117748,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,396.15
117749,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,327.65
117750,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,488.15
117751,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,389.15

In [47]:
# >>> Dataset.
TaskType = Literal['regression', 'binclass', 'multiclass']

# Regression.
task_type: TaskType = 'regression'
n_classes = None
dataset = df_mr
X_cont: np.ndarray = df_mr.iloc[:, :-1].to_numpy()
Y: np.ndarray = df_mr.iloc[:, -1].to_numpy()

task_is_regression = task_type == 'regression'

# >>> Continuous features.
X_cont: np.ndarray = X_cont.astype(np.float32)
n_cont_features = X_cont.shape[1]

# >>> Labels.
if task_type == 'regression':
    Y = Y.astype(np.float32)
else:
    assert n_classes is not None
    Y = Y.astype(np.int64)
    assert set(Y.tolist()) == set(
        range(n_classes)
    ), 'Classification labels must form the range [0, 1, ..., n_classes - 1]'

# >>> Split the dataset.
all_idx = np.arange(len(Y))
trainval_idx, test_idx = sklearn.model_selection.train_test_split(
    all_idx, train_size=0.8
)
train_idx, val_idx = sklearn.model_selection.train_test_split(
    trainval_idx, train_size=0.8
)
data_numpy = {
    'train': {'x_cont': X_cont[train_idx], 'y': Y[train_idx]},
    'val': {'x_cont': X_cont[val_idx], 'y': Y[val_idx]},
    'test': {'x_cont': X_cont[test_idx], 'y': Y[test_idx]},
}

X_cont_train_numpy = data_numpy['train']['x_cont']
noise = (
    np.random.default_rng(0)
    .normal(0.0, 1e-5, X_cont_train_numpy.shape)
    .astype(X_cont_train_numpy.dtype)
)
preprocessing = sklearn.preprocessing.QuantileTransformer(
    n_quantiles=max(min(len(train_idx) // 30, 1000), 10),
    output_distribution='normal',
    subsample=10**9,
).fit(X_cont_train_numpy + noise)
del X_cont_train_numpy

# Apply the preprocessing.
for part in data_numpy:
    data_numpy[part]['x_cont'] = preprocessing.transform(data_numpy[part]['x_cont'])


# Label preprocessing.
class RegressionLabelStats(NamedTuple):
    mean: float
    std: float


Y_train = data_numpy['train']['y'].copy()
if task_type == 'regression':
    # For regression tasks, it is highly recommended to standardize the training labels.
    regression_label_stats = RegressionLabelStats(
        Y_train.mean().item(), Y_train.std().item()
    )
    Y_train = (Y_train - regression_label_stats.mean) / regression_label_stats.std
else:
    regression_label_stats = None

data = {
    part: {k: torch.as_tensor(v, device=device) for k, v in data_numpy[part].items()}
    for part in data_numpy
}

Y_train = torch.as_tensor(Y_train, device=device)
if task_type == 'regression':
    for part in data:
        data[part]['y'] = data[part]['y'].float()
    Y_train = Y_train.float()
    
amp_dtype = (
    torch.bfloat16
    if torch.cuda.is_available() and torch.cuda.is_bf16_supported()
    else torch.float16
    if torch.cuda.is_available()
    else None
)
# Changing False to True will result in faster training on compatible hardware.
amp_enabled = False and amp_dtype is not None
grad_scaler = torch.cuda.amp.GradScaler() if amp_dtype is torch.float16 else None  # type: ignore

# torch.compile
compile_model = False

# fmt: off
print(
    f'Device:        {device.type.upper()}'
    f'\nAMP:           {amp_enabled} (dtype: {amp_dtype})'
    f'\ntorch.compile: {compile_model}'
)
# fmt: on

Device:        CUDA
AMP:           False (dtype: torch.bfloat16)
torch.compile: False

In [55]:
# Choose one of the two configurations below.

# TabM
arch_type = 'tabm'
bins = None

model = Model(
    n_num_features=n_cont_features,
    cat_cardinalities=[], # zero categorical data
    n_classes=n_classes,
    backbone={
        'type': 'MLP',
        'n_blocks': 3 if bins is None else 2,
        'd_block': 512,
        'dropout': 0.1,
    },
    bins=bins,
    num_embeddings=(
        None
        if bins is None
        else {
            'type': 'PiecewiseLinearEmbeddings',
            'd_embedding': 16,
            'activation': False,
            'version': 'B',
        }
    ),
    arch_type=arch_type,
    k=32,
    share_training_batches=True,
).to(device)
optimizer = torch.optim.AdamW(make_parameter_groups(model), lr=2e-3, weight_decay=3e-4)

if compile_model:
    # NOTE
    # `torch.compile` is intentionally called without the `mode` argument
    # (mode="reduce-overhead" caused issues during training with torch==2.0.1).
    model = torch.compile(model)
    evaluation_mode = torch.no_grad
else:
    evaluation_mode = torch.inference_mode
    
@torch.autocast(device.type, enabled=amp_enabled, dtype=amp_dtype)  # type: ignore[code]
def apply_model(part: str, idx: Tensor) -> Tensor:
    return (
        model(
            data[part]['x_cont'][idx],
            data[part]['x_cat'][idx] if 'x_cat' in data[part] else None,
        )
        .squeeze(-1)  # Remove the last dimension for regression tasks.
        .float()
    )


base_loss_fn = F.mse_loss if task_type == 'regression' else F.cross_entropy


def loss_fn(y_pred: Tensor, y_true: Tensor) -> Tensor:
    # TabM produces k predictions. Each of them must be trained separately.
    # (regression)     y_pred.shape == (batch_size, k)
    # (classification) y_pred.shape == (batch_size, k, n_classes)
    k = y_pred.shape[-1 if task_type == 'regression' else -2]
    return base_loss_fn(
        y_pred.flatten(0, 1),
        y_true.repeat_interleave(k) if model.share_training_batches else y_true,
    )


@evaluation_mode()
def evaluate(part: str) -> float:
    import time  # Import time module for timing
    start_time = time.time()  # Start timer
    
    model.eval()

    # When using torch.compile, you may need to reduce the evaluation batch size.
    eval_batch_size = 8096
    y_pred: np.ndarray = (
        torch.cat(
            [
                apply_model(part, idx)
                for idx in torch.arange(len(data[part]['y']), device=device).split(
                    eval_batch_size
                )
            ]
        )
        .cpu()
        .numpy()
    )
    if task_type == 'regression':
        # Transform the predictions back to the original label space.
        assert regression_label_stats is not None
        y_pred = y_pred * regression_label_stats.std + regression_label_stats.mean

    # Compute the mean of the k predictions.
    if task_type != 'regression':
        # For classification, the mean must be computed in the probabily space.
        y_pred = scipy.special.softmax(y_pred, axis=-1)
    y_pred = y_pred.mean(1)

    y_true = data[part]['y'].cpu().numpy()
    mae = sklearn.metrics.mean_absolute_error(y_true, y_pred)
    print(f'MAE ({part} set): {mae:.4f}')  # [ADDED MAE PRINT]
    
    score = (
        -(sklearn.metrics.mean_squared_error(y_true, y_pred) ** 0.5)
        if task_type == 'regression'
        else sklearn.metrics.accuracy_score(y_true, y_pred.argmax(1))
    )
    
    end_time = time.time()  # End timer
    elapsed_time = end_time - start_time  # Calculate elapsed time
    print(f'Evaluation completed in {elapsed_time:.2f} seconds')  # Print timing info
    
    return float(score)  # The higher -- the better.


print(f'Test score before training: {evaluate("test"):.4f}')

MAE (test set): 56.0152
Evaluation completed in 0.53 seconds
Test score before training: -71.2805

In [57]:
n_epochs = 1_000_000_000
patience = 16

train_size = len(train_idx)
batch_size = 256
epoch_size = math.ceil(train_size / batch_size)
best = {
    'val': -math.inf,
    'test': -math.inf,
    'epoch': -1,
}
# Early stopping: the training stops when
# there are more than `patience` consequtive bad updates.
patience = 16
remaining_patience = patience

print('-' * 88 + '\n')
for epoch in range(n_epochs):
    batches = (
        torch.randperm(train_size, device=device).split(batch_size)
        if model.share_training_batches
        else [
            x.transpose(0, 1).flatten()
            for x in torch.rand((model.k, train_size), device=device)
            .argsort(dim=1)
            .split(batch_size, dim=1)
        ]
    )
    for batch_idx in tqdm(batches, desc=f'Epoch {epoch}'):
        model.train()
        optimizer.zero_grad()
        loss = loss_fn(apply_model('train', batch_idx), Y_train[batch_idx])
        if grad_scaler is None:
            loss.backward()
            optimizer.step()
        else:
            grad_scaler.scale(loss).backward()  # type: ignore
            grad_scaler.step(optimizer)
            grad_scaler.update()

    val_score = evaluate('val')
    test_score = evaluate('test')
    print(f'(val) {val_score:.4f} (test) {test_score:.4f}')

    if val_score > best['val']:
        print('🌸 New best epoch! 🌸')
        best = {'val': val_score, 'test': test_score, 'epoch': epoch}
        remaining_patience = patience
    else:
        remaining_patience -= 1

    if remaining_patience < 0:
        break

    print()

print('\n\nResult:')
print(best)

CPU times: user 18 µs, sys: 0 ns, total: 18 µs
Wall time: 75.8 µs
----------------------------------------------------------------------------------------

Epoch 0: 100%|██████████| 295/295 [00:05<00:00, 55.98it/s]

MAE (val set): 32.7708
Evaluation completed in 0.64 seconds
MAE (test set): 32.7285
Evaluation completed in 0.53 seconds
(val) -42.6536 (test) -42.7311
🌸 New best epoch! 🌸

Epoch 1: 100%|██████████| 295/295 [00:05<00:00, 56.75it/s]

MAE (val set): 30.6051
Evaluation completed in 0.67 seconds
MAE (test set): 30.7552
Evaluation completed in 0.53 seconds
(val) -40.1447 (test) -40.3202
🌸 New best epoch! 🌸

Epoch 2: 100%|██████████| 295/295 [00:05<00:00, 57.98it/s]

MAE (val set): 29.6474
Evaluation completed in 0.64 seconds
MAE (test set): 29.7938
Evaluation completed in 0.55 seconds
(val) -39.2961 (test) -39.4782
🌸 New best epoch! 🌸

Epoch 3: 100%|██████████| 295/295 [00:05<00:00, 58.44it/s]

MAE (val set): 29.6049
Evaluation completed in 0.72 seconds
MAE (test set): 29.7029
Evaluation completed in 0.54 seconds
(val) -38.9312 (test) -39.1375
🌸 New best epoch! 🌸

Epoch 4: 100%|██████████| 295/295 [00:05<00:00, 58.40it/s]

MAE (val set): 28.7549
Evaluation completed in 0.63 seconds
MAE (test set): 28.8710
Evaluation completed in 0.52 seconds
(val) -38.2761 (test) -38.4434
🌸 New best epoch! 🌸

Epoch 5: 100%|██████████| 295/295 [00:05<00:00, 58.41it/s]

MAE (val set): 28.9258
Evaluation completed in 0.63 seconds
MAE (test set): 28.9971
Evaluation completed in 0.52 seconds
(val) -38.5116 (test) -38.6498

Epoch 6: 100%|██████████| 295/295 [00:05<00:00, 58.00it/s]

MAE (val set): 28.3337
Evaluation completed in 0.61 seconds
MAE (test set): 28.3774
Evaluation completed in 0.51 seconds
(val) -37.9458 (test) -38.0250
🌸 New best epoch! 🌸

Epoch 7: 100%|██████████| 295/295 [00:05<00:00, 58.32it/s]

MAE (val set): 28.3744
Evaluation completed in 0.62 seconds
MAE (test set): 28.4619
Evaluation completed in 0.51 seconds
(val) -37.7788 (test) -37.9457
🌸 New best epoch! 🌸

Epoch 8: 100%|██████████| 295/295 [00:05<00:00, 58.28it/s]

MAE (val set): 28.4827
Evaluation completed in 0.63 seconds
MAE (test set): 28.6402
Evaluation completed in 0.51 seconds
(val) -37.9049 (test) -38.0945

Epoch 9: 100%|██████████| 295/295 [00:05<00:00, 58.12it/s]

MAE (val set): 28.1526
Evaluation completed in 0.62 seconds
MAE (test set): 28.3016
Evaluation completed in 0.52 seconds
(val) -37.5801 (test) -37.7265
🌸 New best epoch! 🌸

Epoch 10: 100%|██████████| 295/295 [00:05<00:00, 58.06it/s]

MAE (val set): 28.1279
Evaluation completed in 0.62 seconds
MAE (test set): 28.2033
Evaluation completed in 0.52 seconds
(val) -37.5501 (test) -37.6831
🌸 New best epoch! 🌸

Epoch 11: 100%|██████████| 295/295 [00:05<00:00, 57.90it/s]

MAE (val set): 28.1228
Evaluation completed in 0.63 seconds
MAE (test set): 28.3211
Evaluation completed in 0.52 seconds
(val) -37.4780 (test) -37.7888
🌸 New best epoch! 🌸

Epoch 12: 100%|██████████| 295/295 [00:05<00:00, 57.80it/s]

MAE (val set): 28.0957
Evaluation completed in 0.62 seconds
MAE (test set): 28.1980
Evaluation completed in 0.52 seconds
(val) -37.4538 (test) -37.6216
🌸 New best epoch! 🌸

Epoch 13: 100%|██████████| 295/295 [00:05<00:00, 54.98it/s]

MAE (val set): 27.8247
Evaluation completed in 0.76 seconds
MAE (test set): 27.9775
Evaluation completed in 0.55 seconds
(val) -37.2057 (test) -37.4209
🌸 New best epoch! 🌸

Epoch 14: 100%|██████████| 295/295 [00:05<00:00, 56.95it/s]

MAE (val set): 27.7927
Evaluation completed in 0.54 seconds
MAE (test set): 27.8724
Evaluation completed in 0.52 seconds
(val) -37.2596 (test) -37.3413

Epoch 15: 100%|██████████| 295/295 [00:05<00:00, 56.95it/s]

MAE (val set): 27.8989
Evaluation completed in 0.54 seconds
MAE (test set): 28.0448
Evaluation completed in 0.52 seconds
(val) -37.2555 (test) -37.4232

Epoch 16: 100%|██████████| 295/295 [00:05<00:00, 56.46it/s]

MAE (val set): 27.8780
Evaluation completed in 0.63 seconds
MAE (test set): 28.0430
Evaluation completed in 0.52 seconds
(val) -37.2145 (test) -37.4176

Epoch 17: 100%|██████████| 295/295 [00:05<00:00, 55.98it/s]

MAE (val set): 27.6882
Evaluation completed in 0.64 seconds
MAE (test set): 27.8532
Evaluation completed in 0.54 seconds
(val) -37.1496 (test) -37.3285
🌸 New best epoch! 🌸

Epoch 18: 100%|██████████| 295/295 [00:05<00:00, 55.82it/s]

MAE (val set): 27.9331
Evaluation completed in 0.63 seconds
MAE (test set): 28.1010
Evaluation completed in 0.52 seconds
(val) -37.2799 (test) -37.4678

Epoch 19: 100%|██████████| 295/295 [00:05<00:00, 57.82it/s]

MAE (val set): 27.8312
Evaluation completed in 0.62 seconds
MAE (test set): 27.9557
Evaluation completed in 0.52 seconds
(val) -37.2286 (test) -37.4176

Epoch 20: 100%|██████████| 295/295 [00:05<00:00, 57.85it/s]

MAE (val set): 27.5977
Evaluation completed in 0.64 seconds
MAE (test set): 27.7549
Evaluation completed in 0.52 seconds
(val) -37.0939 (test) -37.3042
🌸 New best epoch! 🌸

Epoch 21: 100%|██████████| 295/295 [00:05<00:00, 57.85it/s]

MAE (val set): 27.8090
Evaluation completed in 0.63 seconds
MAE (test set): 27.9686
Evaluation completed in 0.53 seconds
(val) -37.2247 (test) -37.4293

Epoch 22: 100%|██████████| 295/295 [00:05<00:00, 56.85it/s]

MAE (val set): 27.7048
Evaluation completed in 0.52 seconds
MAE (test set): 27.9268
Evaluation completed in 0.52 seconds
(val) -37.1014 (test) -37.3507

Epoch 23: 100%|██████████| 295/295 [00:05<00:00, 57.78it/s]

MAE (val set): 27.6367
Evaluation completed in 0.63 seconds
MAE (test set): 27.7956
Evaluation completed in 0.52 seconds
(val) -37.1009 (test) -37.2560

Epoch 24: 100%|██████████| 295/295 [00:05<00:00, 56.21it/s]

MAE (val set): 27.5581
Evaluation completed in 0.48 seconds
MAE (test set): 27.6967
Evaluation completed in 0.52 seconds
(val) -37.0744 (test) -37.2514
🌸 New best epoch! 🌸

Epoch 25: 100%|██████████| 295/295 [00:05<00:00, 57.06it/s]

MAE (val set): 27.6820
Evaluation completed in 0.63 seconds
MAE (test set): 27.7864
Evaluation completed in 0.52 seconds
(val) -37.1971 (test) -37.3532

Epoch 26: 100%|██████████| 295/295 [00:05<00:00, 56.82it/s]

MAE (val set): 27.6311
Evaluation completed in 0.62 seconds
MAE (test set): 27.8092
Evaluation completed in 0.52 seconds
(val) -37.0552 (test) -37.2841
🌸 New best epoch! 🌸

Epoch 27: 100%|██████████| 295/295 [00:05<00:00, 56.47it/s]

MAE (val set): 27.5658
Evaluation completed in 0.63 seconds
MAE (test set): 27.7591
Evaluation completed in 0.52 seconds
(val) -36.9629 (test) -37.1549
🌸 New best epoch! 🌸

Epoch 28: 100%|██████████| 295/295 [00:05<00:00, 56.14it/s]

MAE (val set): 27.7892
Evaluation completed in 0.63 seconds
MAE (test set): 27.9232
Evaluation completed in 0.52 seconds
(val) -37.2373 (test) -37.4519

Epoch 29: 100%|██████████| 295/295 [00:05<00:00, 55.94it/s]

MAE (val set): 27.5875
Evaluation completed in 0.63 seconds
MAE (test set): 27.7511
Evaluation completed in 0.52 seconds
(val) -37.0743 (test) -37.2904

Epoch 30: 100%|██████████| 295/295 [00:05<00:00, 55.58it/s]

MAE (val set): 27.8045
Evaluation completed in 0.63 seconds
MAE (test set): 27.9430
Evaluation completed in 0.52 seconds
(val) -37.2601 (test) -37.4897

Epoch 31: 100%|██████████| 295/295 [00:05<00:00, 54.40it/s]

MAE (val set): 27.8104
Evaluation completed in 0.54 seconds
MAE (test set): 27.9274
Evaluation completed in 0.52 seconds
(val) -37.2536 (test) -37.4296

Epoch 32: 100%|██████████| 295/295 [00:05<00:00, 54.17it/s]

MAE (val set): 27.4712
Evaluation completed in 0.61 seconds
MAE (test set): 27.6436
Evaluation completed in 0.55 seconds
(val) -36.9241 (test) -37.1317
🌸 New best epoch! 🌸

Epoch 33: 100%|██████████| 295/295 [00:05<00:00, 54.40it/s]

MAE (val set): 27.4466
Evaluation completed in 0.65 seconds
MAE (test set): 27.5883
Evaluation completed in 0.55 seconds
(val) -36.9620 (test) -37.0972

Epoch 34: 100%|██████████| 295/295 [00:05<00:00, 56.74it/s]

MAE (val set): 27.5696
Evaluation completed in 0.65 seconds
MAE (test set): 27.7193
Evaluation completed in 0.55 seconds
(val) -37.0869 (test) -37.2511

Epoch 35: 100%|██████████| 295/295 [00:05<00:00, 57.56it/s]

MAE (val set): 27.5470
Evaluation completed in 0.64 seconds
MAE (test set): 27.7331
Evaluation completed in 0.52 seconds
(val) -36.9671 (test) -37.2181

Epoch 36: 100%|██████████| 295/295 [00:05<00:00, 57.77it/s]

MAE (val set): 27.5294
Evaluation completed in 0.63 seconds
MAE (test set): 27.6616
Evaluation completed in 0.52 seconds
(val) -37.0343 (test) -37.2374

Epoch 37: 100%|██████████| 295/295 [00:05<00:00, 56.38it/s]

MAE (val set): 27.5510
Evaluation completed in 0.50 seconds
MAE (test set): 27.7749
Evaluation completed in 0.52 seconds
(val) -36.9289 (test) -37.1737

Epoch 38: 100%|██████████| 295/295 [00:05<00:00, 57.74it/s]

MAE (val set): 27.8228
Evaluation completed in 0.63 seconds
MAE (test set): 27.9664
Evaluation completed in 0.52 seconds
(val) -37.3115 (test) -37.5702

Epoch 39: 100%|██████████| 295/295 [00:05<00:00, 57.73it/s]

MAE (val set): 27.4893
Evaluation completed in 0.63 seconds
MAE (test set): 27.6605
Evaluation completed in 0.52 seconds
(val) -36.9216 (test) -37.1281
🌸 New best epoch! 🌸

Epoch 40: 100%|██████████| 295/295 [00:05<00:00, 56.72it/s]

MAE (val set): 27.5395
Evaluation completed in 0.53 seconds
MAE (test set): 27.6965
Evaluation completed in 0.52 seconds
(val) -37.0063 (test) -37.1945

Epoch 41: 100%|██████████| 295/295 [00:05<00:00, 57.73it/s]

MAE (val set): 27.5212
Evaluation completed in 0.65 seconds
MAE (test set): 27.6828
Evaluation completed in 0.52 seconds
(val) -37.0287 (test) -37.2201

Epoch 42: 100%|██████████| 295/295 [00:05<00:00, 55.61it/s]

MAE (val set): 27.7554
Evaluation completed in 0.43 seconds
MAE (test set): 27.8981
Evaluation completed in 0.52 seconds
(val) -37.1341 (test) -37.3261

Epoch 43: 100%|██████████| 295/295 [00:05<00:00, 57.40it/s]

MAE (val set): 27.5411
Evaluation completed in 0.61 seconds
MAE (test set): 27.6846
Evaluation completed in 0.52 seconds
(val) -36.9907 (test) -37.2004

Epoch 44: 100%|██████████| 295/295 [00:05<00:00, 57.20it/s]

MAE (val set): 27.6078
Evaluation completed in 0.63 seconds
MAE (test set): 27.7498
Evaluation completed in 0.52 seconds
(val) -37.1330 (test) -37.3609

Epoch 45: 100%|██████████| 295/295 [00:05<00:00, 56.93it/s]

MAE (val set): 27.4959
Evaluation completed in 0.63 seconds
MAE (test set): 27.6165
Evaluation completed in 0.52 seconds
(val) -37.1484 (test) -37.3115

Epoch 46: 100%|██████████| 295/295 [00:05<00:00, 56.44it/s]

MAE (val set): 27.4925
Evaluation completed in 0.63 seconds
MAE (test set): 27.6538
Evaluation completed in 0.53 seconds
(val) -37.0286 (test) -37.2538

Epoch 47: 100%|██████████| 295/295 [00:05<00:00, 56.47it/s]

MAE (val set): 27.7463
Evaluation completed in 0.63 seconds
MAE (test set): 27.8880
Evaluation completed in 0.53 seconds
(val) -37.0920 (test) -37.3136

Epoch 48: 100%|██████████| 295/295 [00:05<00:00, 56.37it/s]

MAE (val set): 27.5651
Evaluation completed in 0.59 seconds
MAE (test set): 27.6571
Evaluation completed in 0.52 seconds
(val) -37.1145 (test) -37.2520

Epoch 49: 100%|██████████| 295/295 [00:05<00:00, 55.79it/s]

MAE (val set): 27.7426
Evaluation completed in 0.63 seconds
MAE (test set): 27.8674
Evaluation completed in 0.53 seconds
(val) -37.2713 (test) -37.4627

Epoch 50: 100%|██████████| 295/295 [00:05<00:00, 56.78it/s]

MAE (val set): 27.3936
Evaluation completed in 0.64 seconds
MAE (test set): 27.5625
Evaluation completed in 0.52 seconds
(val) -37.0167 (test) -37.2132

Epoch 51: 100%|██████████| 295/295 [00:05<00:00, 57.71it/s]

MAE (val set): 27.6818
Evaluation completed in 0.63 seconds
MAE (test set): 27.7988
Evaluation completed in 0.52 seconds
(val) -37.1915 (test) -37.3903

Epoch 52: 100%|██████████| 295/295 [00:05<00:00, 57.71it/s]

MAE (val set): 27.5299
Evaluation completed in 0.63 seconds
MAE (test set): 27.6852
Evaluation completed in 0.52 seconds
(val) -36.9398 (test) -37.1085

Epoch 53: 100%|██████████| 295/295 [00:05<00:00, 57.76it/s]

MAE (val set): 27.5696
Evaluation completed in 0.63 seconds
MAE (test set): 27.7076
Evaluation completed in 0.52 seconds
(val) -36.9938 (test) -37.1799

Epoch 54: 100%|██████████| 295/295 [00:05<00:00, 57.72it/s]

MAE (val set): 27.6264
Evaluation completed in 0.63 seconds
MAE (test set): 27.7320
Evaluation completed in 0.54 seconds
(val) -37.0290 (test) -37.2300

Epoch 55: 100%|██████████| 295/295 [00:05<00:00, 57.70it/s]

MAE (val set): 27.4523
Evaluation completed in 0.63 seconds
MAE (test set): 27.5992
Evaluation completed in 0.52 seconds
(val) -37.0255 (test) -37.2404

Epoch 56: 100%|██████████| 295/295 [00:05<00:00, 57.73it/s]

MAE (val set): 27.7055
Evaluation completed in 0.63 seconds
MAE (test set): 27.8388
Evaluation completed in 0.53 seconds
(val) -37.0619 (test) -37.2726


Result:
{'val': -36.92161711716965, 'test': -37.12807259223218, 'epoch': 39}

In [58]:
print('\n\nResult:')
print(best)

Result:
{'val': -36.92161711716965, 'test': -37.12807259223218, 'epoch': 39}

In [59]:
df_cb

,0,2,3,4,5,6,7,8,9,10,...,591,592,593,594,595,596,597,598,599,MP
0,0.383230,0.517380,-0.280701,0.008003,0.219609,0.726157,-0.362477,-0.405935,0.430935,-0.859224,...,-0.032460,0.060221,0.710166,0.107282,-0.070665,-0.364548,0.524827,-0.219044,0.296993,355.15
1,0.053002,0.046581,-0.045467,0.265602,0.121656,0.248467,-0.471550,-0.289988,-0.205801,-0.737166,...,0.247456,-0.045622,0.724922,0.419859,-0.171350,-0.007923,0.040881,0.082113,0.109209,373.65
2,0.650106,1.011580,0.463880,-0.496643,0.410833,0.831479,0.182609,-0.388742,-0.045355,-0.275201,...,-0.135553,0.645528,-0.111434,0.043732,0.342703,0.008101,0.571934,0.079836,-0.283608,373.75
3,-0.209592,-0.243905,0.176476,0.517554,0.026938,-0.402658,-0.327484,-0.280088,-0.028855,-0.180202,...,-0.285914,-0.212273,0.117536,0.522993,-0.621208,0.539129,0.111357,0.331581,-0.086567,373.70
4,0.122910,-0.064467,0.686867,0.239316,-0.103160,-0.167726,-0.105149,-0.489707,-0.066420,-0.162347,...,-0.134271,-0.102144,0.248343,0.010503,0.611926,0.318152,-0.114292,0.528896,0.231508,374.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117747,0.217291,0.508175,-0.111223,0.113894,0.382003,0.612502,-0.328363,-0.080576,-0.240976,0.293184,...,0.423016,0.121292,-0.209866,0.408977,0.190961,-0.239830,0.351643,0.320553,-0.202831,395.65
117748,-0.067462,0.677433,-0.245434,0.440785,0.263820,0.551249,-0.395648,-0.091693,-0.263357,-0.179503,...,0.689446,0.232293,-0.200617,0.187333,0.386570,-0.406295,0.402920,0.360022,-0.122600,396.15
117749,0.181496,0.512077,-0.280476,0.437974,-0.027109,0.723539,-0.385805,-0.248053,-0.145493,0.086625,...,0.213210,0.422839,0.372862,0.592165,0.328713,-0.316499,0.294498,0.418610,-0.106374,327.65
117750,-0.098858,0.585181,-0.392476,0.777918,0.295732,0.250359,-0.306643,0.118758,-0.226906,-0.079321,...,0.544464,0.256705,0.045325,0.412411,0.184333,-0.314178,-0.058447,0.660162,-0.180543,488.15
117751,0.033644,0.599846,-0.234451,0.553492,0.294395,0.216537,-0.238240,0.011329,-0.016467,-0.226111,...,0.506719,0.112179,-0.074024,0.264317,0.325658,-0.337432,-0.028559,0.557561,-0.184028,389.15

In [60]:
df_mf

,0,1,2,3,4,5,6,7,8,9,...,759,760,761,762,763,764,765,766,767,MP
0,0.232754,0.039662,0.603345,0.434351,-0.235619,-0.008117,-0.240256,-0.327148,-0.622383,-0.242045,...,0.511787,0.017956,-0.102726,0.593849,-0.322905,-2.748505,0.264649,-0.493542,0.170734,355.15
1,-0.035469,0.244099,0.824150,0.871007,0.381988,0.018918,-0.171494,-0.681534,0.314292,0.073357,...,-0.444052,-0.211882,-0.301885,-0.089473,-0.258444,-2.224507,0.016750,-0.915583,0.149851,373.65
2,-0.014357,0.257718,0.659238,0.541999,0.342051,0.048318,0.188520,-0.241498,-0.025705,-0.207805,...,-0.124264,0.174638,-0.048913,-0.015672,-0.385274,-2.904102,0.212661,-0.588502,-0.315535,373.75
3,0.392396,0.213285,0.820162,0.444167,-0.283028,-0.213827,0.098154,-0.381828,0.016981,-0.291995,...,-0.253576,-0.132808,0.243490,0.575032,0.081913,-2.777802,0.065183,-0.286023,-0.647094,373.70
4,0.630157,0.129021,0.930085,0.348113,-0.079924,-0.057398,0.470295,0.097515,-0.180795,-0.171304,...,0.135372,-0.524551,0.513307,-0.236967,-0.219924,-3.077367,0.617281,-0.337038,-0.176350,374.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117747,0.536852,0.122638,0.304402,-0.319562,-0.675866,0.010863,-0.525479,-0.008692,-0.520580,-0.474743,...,-0.322050,-0.702077,0.462894,0.641812,-0.209804,-2.338952,0.601882,-0.391491,-0.380140,395.65
117748,-0.091166,0.245632,-0.179062,0.299272,-0.800757,-0.122798,-0.938942,-0.098464,0.014622,-0.054302,...,-0.299069,0.062411,0.707462,0.116971,-0.379527,-2.399415,0.433567,-0.402556,-0.216447,396.15
117749,0.463926,0.466987,0.087009,0.034810,-1.054933,-0.277966,-0.886445,-0.060067,-0.231398,0.083403,...,0.006923,-0.156032,0.417531,0.423048,-0.546653,-2.341095,0.170920,-0.561870,-0.619896,327.65
117750,0.502144,0.065869,0.162445,-0.160113,-1.070973,-0.249068,-0.573376,-0.082146,0.197232,-0.234873,...,-0.269982,-0.340257,0.310560,0.339327,-0.547660,-2.511800,0.631499,-0.330420,-0.576203,488.15
117751,-0.164626,0.498604,-0.480907,0.286132,-0.866054,-0.548921,-0.711837,0.196849,0.095999,-0.226699,...,-0.135179,-0.376027,0.247147,0.514326,-0.289037,-1.974172,0.163462,-0.636052,-0.142280,389.15

In [62]:
joined_df = pd.concat([df_cb.drop(columns=['MP']), df_mf], axis=1)
joined_df

,0,2,3,4,5,6,7,8,9,10,...,759,760,761,762,763,764,765,766,767,MP
0,0.383230,0.517380,-0.280701,0.008003,0.219609,0.726157,-0.362477,-0.405935,0.430935,-0.859224,...,0.511787,0.017956,-0.102726,0.593849,-0.322905,-2.748505,0.264649,-0.493542,0.170734,355.15
1,0.053002,0.046581,-0.045467,0.265602,0.121656,0.248467,-0.471550,-0.289988,-0.205801,-0.737166,...,-0.444052,-0.211882,-0.301885,-0.089473,-0.258444,-2.224507,0.016750,-0.915583,0.149851,373.65
2,0.650106,1.011580,0.463880,-0.496643,0.410833,0.831479,0.182609,-0.388742,-0.045355,-0.275201,...,-0.124264,0.174638,-0.048913,-0.015672,-0.385274,-2.904102,0.212661,-0.588502,-0.315535,373.75
3,-0.209592,-0.243905,0.176476,0.517554,0.026938,-0.402658,-0.327484,-0.280088,-0.028855,-0.180202,...,-0.253576,-0.132808,0.243490,0.575032,0.081913,-2.777802,0.065183,-0.286023,-0.647094,373.70
4,0.122910,-0.064467,0.686867,0.239316,-0.103160,-0.167726,-0.105149,-0.489707,-0.066420,-0.162347,...,0.135372,-0.524551,0.513307,-0.236967,-0.219924,-3.077367,0.617281,-0.337038,-0.176350,374.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117747,0.217291,0.508175,-0.111223,0.113894,0.382003,0.612502,-0.328363,-0.080576,-0.240976,0.293184,...,-0.322050,-0.702077,0.462894,0.641812,-0.209804,-2.338952,0.601882,-0.391491,-0.380140,395.65
117748,-0.067462,0.677433,-0.245434,0.440785,0.263820,0.551249,-0.395648,-0.091693,-0.263357,-0.179503,...,-0.299069,0.062411,0.707462,0.116971,-0.379527,-2.399415,0.433567,-0.402556,-0.216447,396.15
117749,0.181496,0.512077,-0.280476,0.437974,-0.027109,0.723539,-0.385805,-0.248053,-0.145493,0.086625,...,0.006923,-0.156032,0.417531,0.423048,-0.546653,-2.341095,0.170920,-0.561870,-0.619896,327.65
117750,-0.098858,0.585181,-0.392476,0.777918,0.295732,0.250359,-0.306643,0.118758,-0.226906,-0.079321,...,-0.269982,-0.340257,0.310560,0.339327,-0.547660,-2.511800,0.631499,-0.330420,-0.576203,488.15
117751,0.033644,0.599846,-0.234451,0.553492,0.294395,0.216537,-0.238240,0.011329,-0.016467,-0.226111,...,-0.135179,-0.376027,0.247147,0.514326,-0.289037,-1.974172,0.163462,-0.636052,-0.142280,389.15

In [63]:
# >>> Dataset.
TaskType = Literal['regression', 'binclass', 'multiclass']

# Regression.
task_type: TaskType = 'regression'
n_classes = None
dataset = joined_df
X_cont: np.ndarray = joined_df.iloc[:, :-1].to_numpy()
Y: np.ndarray = joined_df.iloc[:, -1].to_numpy()

task_is_regression = task_type == 'regression'

# >>> Continuous features.
X_cont: np.ndarray = X_cont.astype(np.float32)
n_cont_features = X_cont.shape[1]

# >>> Labels.
if task_type == 'regression':
    Y = Y.astype(np.float32)
else:
    assert n_classes is not None
    Y = Y.astype(np.int64)
    assert set(Y.tolist()) == set(
        range(n_classes)
    ), 'Classification labels must form the range [0, 1, ..., n_classes - 1]'

# >>> Split the dataset.
all_idx = np.arange(len(Y))
trainval_idx, test_idx = sklearn.model_selection.train_test_split(
    all_idx, train_size=0.8
)
train_idx, val_idx = sklearn.model_selection.train_test_split(
    trainval_idx, train_size=0.8
)
data_numpy = {
    'train': {'x_cont': X_cont[train_idx], 'y': Y[train_idx]},
    'val': {'x_cont': X_cont[val_idx], 'y': Y[val_idx]},
    'test': {'x_cont': X_cont[test_idx], 'y': Y[test_idx]},
}

X_cont_train_numpy = data_numpy['train']['x_cont']
noise = (
    np.random.default_rng(0)
    .normal(0.0, 1e-5, X_cont_train_numpy.shape)
    .astype(X_cont_train_numpy.dtype)
)
preprocessing = sklearn.preprocessing.QuantileTransformer(
    n_quantiles=max(min(len(train_idx) // 30, 1000), 10),
    output_distribution='normal',
    subsample=10**9,
).fit(X_cont_train_numpy + noise)
del X_cont_train_numpy

# Apply the preprocessing.
for part in data_numpy:
    data_numpy[part]['x_cont'] = preprocessing.transform(data_numpy[part]['x_cont'])


# Label preprocessing.
class RegressionLabelStats(NamedTuple):
    mean: float
    std: float


Y_train = data_numpy['train']['y'].copy()
if task_type == 'regression':
    # For regression tasks, it is highly recommended to standardize the training labels.
    regression_label_stats = RegressionLabelStats(
        Y_train.mean().item(), Y_train.std().item()
    )
    Y_train = (Y_train - regression_label_stats.mean) / regression_label_stats.std
else:
    regression_label_stats = None

data = {
    part: {k: torch.as_tensor(v, device=device) for k, v in data_numpy[part].items()}
    for part in data_numpy
}

Y_train = torch.as_tensor(Y_train, device=device)
if task_type == 'regression':
    for part in data:
        data[part]['y'] = data[part]['y'].float()
    Y_train = Y_train.float()
    
amp_dtype = (
    torch.bfloat16
    if torch.cuda.is_available() and torch.cuda.is_bf16_supported()
    else torch.float16
    if torch.cuda.is_available()
    else None
)
# Changing False to True will result in faster training on compatible hardware.
amp_enabled = False and amp_dtype is not None
grad_scaler = torch.cuda.amp.GradScaler() if amp_dtype is torch.float16 else None  # type: ignore

# torch.compile
compile_model = False

# fmt: off
print(
    f'Device:        {device.type.upper()}'
    f'\nAMP:           {amp_enabled} (dtype: {amp_dtype})'
    f'\ntorch.compile: {compile_model}'
)
# fmt: on

Device:        CUDA
AMP:           False (dtype: torch.bfloat16)
torch.compile: False

In [64]:
# Choose one of the two configurations below.

# TabM
arch_type = 'tabm'
bins = None

model = Model(
    n_num_features=n_cont_features,
    cat_cardinalities=[], # zero categorical data
    n_classes=n_classes,
    backbone={
        'type': 'MLP',
        'n_blocks': 3 if bins is None else 2,
        'd_block': 512,
        'dropout': 0.1,
    },
    bins=bins,
    num_embeddings=(
        None
        if bins is None
        else {
            'type': 'PiecewiseLinearEmbeddings',
            'd_embedding': 16,
            'activation': False,
            'version': 'B',
        }
    ),
    arch_type=arch_type,
    k=32,
    share_training_batches=True,
).to(device)
optimizer = torch.optim.AdamW(make_parameter_groups(model), lr=2e-3, weight_decay=3e-4)

if compile_model:
    # NOTE
    # `torch.compile` is intentionally called without the `mode` argument
    # (mode="reduce-overhead" caused issues during training with torch==2.0.1).
    model = torch.compile(model)
    evaluation_mode = torch.no_grad
else:
    evaluation_mode = torch.inference_mode
    
@torch.autocast(device.type, enabled=amp_enabled, dtype=amp_dtype)  # type: ignore[code]
def apply_model(part: str, idx: Tensor) -> Tensor:
    return (
        model(
            data[part]['x_cont'][idx],
            data[part]['x_cat'][idx] if 'x_cat' in data[part] else None,
        )
        .squeeze(-1)  # Remove the last dimension for regression tasks.
        .float()
    )


base_loss_fn = F.mse_loss if task_type == 'regression' else F.cross_entropy


def loss_fn(y_pred: Tensor, y_true: Tensor) -> Tensor:
    # TabM produces k predictions. Each of them must be trained separately.
    # (regression)     y_pred.shape == (batch_size, k)
    # (classification) y_pred.shape == (batch_size, k, n_classes)
    k = y_pred.shape[-1 if task_type == 'regression' else -2]
    return base_loss_fn(
        y_pred.flatten(0, 1),
        y_true.repeat_interleave(k) if model.share_training_batches else y_true,
    )


@evaluation_mode()
def evaluate(part: str) -> float:
    import time  # Import time module for timing
    start_time = time.time()  # Start timer
    
    model.eval()

    # When using torch.compile, you may need to reduce the evaluation batch size.
    eval_batch_size = 8096
    y_pred: np.ndarray = (
        torch.cat(
            [
                apply_model(part, idx)
                for idx in torch.arange(len(data[part]['y']), device=device).split(
                    eval_batch_size
                )
            ]
        )
        .cpu()
        .numpy()
    )
    if task_type == 'regression':
        # Transform the predictions back to the original label space.
        assert regression_label_stats is not None
        y_pred = y_pred * regression_label_stats.std + regression_label_stats.mean

    # Compute the mean of the k predictions.
    if task_type != 'regression':
        # For classification, the mean must be computed in the probabily space.
        y_pred = scipy.special.softmax(y_pred, axis=-1)
    y_pred = y_pred.mean(1)

    y_true = data[part]['y'].cpu().numpy()
    mae = sklearn.metrics.mean_absolute_error(y_true, y_pred)
    print(f'MAE ({part} set): {mae:.4f}')  # [ADDED MAE PRINT]
    
    score = (
        -(sklearn.metrics.mean_squared_error(y_true, y_pred) ** 0.5)
        if task_type == 'regression'
        else sklearn.metrics.accuracy_score(y_true, y_pred.argmax(1))
    )
    
    end_time = time.time()  # End timer
    elapsed_time = end_time - start_time  # Calculate elapsed time
    print(f'Evaluation completed in {elapsed_time:.2f} seconds')  # Print timing info
    
    return float(score)  # The higher -- the better.


print(f'Test score before training: {evaluate("test"):.4f}')

MAE (test set): 56.2889
Evaluation completed in 0.29 seconds
Test score before training: -71.3370

In [65]:
n_epochs = 1_000_000_000
patience = 16

train_size = len(train_idx)
batch_size = 256
epoch_size = math.ceil(train_size / batch_size)
best = {
    'val': -math.inf,
    'test': -math.inf,
    'epoch': -1,
}
# Early stopping: the training stops when
# there are more than `patience` consequtive bad updates.
patience = 16
remaining_patience = patience

print('-' * 88 + '\n')
for epoch in range(n_epochs):
    batches = (
        torch.randperm(train_size, device=device).split(batch_size)
        if model.share_training_batches
        else [
            x.transpose(0, 1).flatten()
            for x in torch.rand((model.k, train_size), device=device)
            .argsort(dim=1)
            .split(batch_size, dim=1)
        ]
    )
    for batch_idx in tqdm(batches, desc=f'Epoch {epoch}'):
        model.train()
        optimizer.zero_grad()
        loss = loss_fn(apply_model('train', batch_idx), Y_train[batch_idx])
        if grad_scaler is None:
            loss.backward()
            optimizer.step()
        else:
            grad_scaler.scale(loss).backward()  # type: ignore
            grad_scaler.step(optimizer)
            grad_scaler.update()

    val_score = evaluate('val')
    test_score = evaluate('test')
    print(f'(val) {val_score:.4f} (test) {test_score:.4f}')

    if val_score > best['val']:
        print('🌸 New best epoch! 🌸')
        best = {'val': val_score, 'test': test_score, 'epoch': epoch}
        remaining_patience = patience
    else:
        remaining_patience -= 1

    if remaining_patience < 0:
        break

    print()

print('\n\nResult:')
print(best)

----------------------------------------------------------------------------------------

Epoch 0: 100%|██████████| 295/295 [00:02<00:00, 105.70it/s]

MAE (val set): 30.2410
Evaluation completed in 0.34 seconds
MAE (test set): 30.5868
Evaluation completed in 0.27 seconds
(val) -39.2152 (test) -39.7790
🌸 New best epoch! 🌸

Epoch 1: 100%|██████████| 295/295 [00:02<00:00, 105.41it/s]

MAE (val set): 29.9915
Evaluation completed in 0.34 seconds
MAE (test set): 30.3770
Evaluation completed in 0.28 seconds
(val) -38.8047 (test) -39.3950
🌸 New best epoch! 🌸

Epoch 2: 100%|██████████| 295/295 [00:02<00:00, 105.03it/s]

MAE (val set): 30.2575
Evaluation completed in 0.34 seconds
MAE (test set): 30.6654
Evaluation completed in 0.28 seconds
(val) -39.2479 (test) -39.7601

Epoch 3: 100%|██████████| 295/295 [00:02<00:00, 104.70it/s]

MAE (val set): 28.6123
Evaluation completed in 0.34 seconds
MAE (test set): 29.1104
Evaluation completed in 0.28 seconds
(val) -37.5149 (test) -38.1827
🌸 New best epoch! 🌸

Epoch 4: 100%|██████████| 295/295 [00:02<00:00, 104.64it/s]

MAE (val set): 28.8468
Evaluation completed in 0.34 seconds
MAE (test set): 29.3835
Evaluation completed in 0.28 seconds
(val) -37.6185 (test) -38.3635

Epoch 5: 100%|██████████| 295/295 [00:02<00:00, 104.64it/s]

MAE (val set): 28.5471
Evaluation completed in 0.34 seconds
MAE (test set): 28.9682
Evaluation completed in 0.28 seconds
(val) -37.2837 (test) -37.9076
🌸 New best epoch! 🌸

Epoch 6: 100%|██████████| 295/295 [00:02<00:00, 104.54it/s]

MAE (val set): 28.1848
Evaluation completed in 0.34 seconds
MAE (test set): 28.7040
Evaluation completed in 0.28 seconds
(val) -36.8293 (test) -37.5760
🌸 New best epoch! 🌸

Epoch 7: 100%|██████████| 295/295 [00:02<00:00, 104.51it/s]

MAE (val set): 28.0245
Evaluation completed in 0.34 seconds
MAE (test set): 28.5536
Evaluation completed in 0.28 seconds
(val) -36.6749 (test) -37.4032
🌸 New best epoch! 🌸

Epoch 8: 100%|██████████| 295/295 [00:02<00:00, 104.46it/s]

MAE (val set): 27.9892
Evaluation completed in 0.34 seconds
MAE (test set): 28.4227
Evaluation completed in 0.28 seconds
(val) -36.5198 (test) -37.1690
🌸 New best epoch! 🌸

Epoch 9: 100%|██████████| 295/295 [00:02<00:00, 104.44it/s]

MAE (val set): 27.4721
Evaluation completed in 0.34 seconds
MAE (test set): 27.9932
Evaluation completed in 0.28 seconds
(val) -36.1251 (test) -36.9015
🌸 New best epoch! 🌸

Epoch 10: 100%|██████████| 295/295 [00:02<00:00, 104.09it/s]

MAE (val set): 28.0036
Evaluation completed in 0.34 seconds
MAE (test set): 28.5406
Evaluation completed in 0.28 seconds
(val) -36.4814 (test) -37.2223

Epoch 11: 100%|██████████| 295/295 [00:02<00:00, 104.07it/s]

MAE (val set): 27.3182
Evaluation completed in 0.34 seconds
MAE (test set): 27.9002
Evaluation completed in 0.28 seconds
(val) -36.1577 (test) -36.9772

Epoch 12: 100%|██████████| 295/295 [00:02<00:00, 104.06it/s]

MAE (val set): 27.3148
Evaluation completed in 0.34 seconds
MAE (test set): 27.7791
Evaluation completed in 0.28 seconds
(val) -35.8588 (test) -36.5940
🌸 New best epoch! 🌸

Epoch 13: 100%|██████████| 295/295 [00:02<00:00, 104.03it/s]

MAE (val set): 27.4596
Evaluation completed in 0.34 seconds
MAE (test set): 27.8348
Evaluation completed in 0.28 seconds
(val) -36.0201 (test) -36.6919

Epoch 14: 100%|██████████| 295/295 [00:02<00:00, 103.98it/s]

MAE (val set): 27.2417
Evaluation completed in 0.34 seconds
MAE (test set): 27.6625
Evaluation completed in 0.28 seconds
(val) -35.7606 (test) -36.3961
🌸 New best epoch! 🌸

Epoch 15: 100%|██████████| 295/295 [00:02<00:00, 103.96it/s]

MAE (val set): 26.9108
Evaluation completed in 0.34 seconds
MAE (test set): 27.4276
Evaluation completed in 0.28 seconds
(val) -35.5148 (test) -36.3050
🌸 New best epoch! 🌸

Epoch 16: 100%|██████████| 295/295 [00:02<00:00, 103.96it/s]

MAE (val set): 27.2255
Evaluation completed in 0.34 seconds
MAE (test set): 27.7253
Evaluation completed in 0.28 seconds
(val) -35.6529 (test) -36.4194

Epoch 17: 100%|██████████| 295/295 [00:02<00:00, 103.91it/s]

MAE (val set): 27.0729
Evaluation completed in 0.34 seconds
MAE (test set): 27.6115
Evaluation completed in 0.28 seconds
(val) -35.7866 (test) -36.6326

Epoch 18: 100%|██████████| 295/295 [00:02<00:00, 103.91it/s]

MAE (val set): 27.1751
Evaluation completed in 0.34 seconds
MAE (test set): 27.6786
Evaluation completed in 0.28 seconds
(val) -35.7502 (test) -36.5153

Epoch 19: 100%|██████████| 295/295 [00:02<00:00, 103.90it/s]

MAE (val set): 27.3061
Evaluation completed in 0.34 seconds
MAE (test set): 27.7758
Evaluation completed in 0.28 seconds
(val) -35.8887 (test) -36.5804

Epoch 20: 100%|██████████| 295/295 [00:02<00:00, 103.88it/s]

MAE (val set): 26.7170
Evaluation completed in 0.34 seconds
MAE (test set): 27.2914
Evaluation completed in 0.28 seconds
(val) -35.6464 (test) -36.4920

Epoch 21: 100%|██████████| 295/295 [00:02<00:00, 103.89it/s]

MAE (val set): 27.1126
Evaluation completed in 0.34 seconds
MAE (test set): 27.5950
Evaluation completed in 0.28 seconds
(val) -35.7712 (test) -36.4871

Epoch 22: 100%|██████████| 295/295 [00:02<00:00, 103.84it/s]

MAE (val set): 27.1097
Evaluation completed in 0.34 seconds
MAE (test set): 27.5525
Evaluation completed in 0.28 seconds
(val) -35.6348 (test) -36.3664

Epoch 23: 100%|██████████| 295/295 [00:02<00:00, 103.83it/s]

MAE (val set): 26.5074
Evaluation completed in 0.34 seconds
MAE (test set): 27.0246
Evaluation completed in 0.28 seconds
(val) -35.2350 (test) -36.0373
🌸 New best epoch! 🌸

Epoch 24: 100%|██████████| 295/295 [00:02<00:00, 103.84it/s]

MAE (val set): 27.4481
Evaluation completed in 0.35 seconds
MAE (test set): 27.8824
Evaluation completed in 0.28 seconds
(val) -35.8732 (test) -36.5250

Epoch 25: 100%|██████████| 295/295 [00:02<00:00, 103.56it/s]

MAE (val set): 27.3390
Evaluation completed in 0.34 seconds
MAE (test set): 27.8555
Evaluation completed in 0.28 seconds
(val) -35.8027 (test) -36.5545

Epoch 26: 100%|██████████| 295/295 [00:02<00:00, 103.56it/s]

MAE (val set): 26.8808
Evaluation completed in 0.34 seconds
MAE (test set): 27.3609
Evaluation completed in 0.28 seconds
(val) -35.3416 (test) -36.0705

Epoch 27: 100%|██████████| 295/295 [00:02<00:00, 103.55it/s]

MAE (val set): 26.7311
Evaluation completed in 0.34 seconds
MAE (test set): 27.1977
Evaluation completed in 0.28 seconds
(val) -35.3252 (test) -36.0198

Epoch 28: 100%|██████████| 295/295 [00:02<00:00, 103.53it/s]

MAE (val set): 26.6531
Evaluation completed in 0.34 seconds
MAE (test set): 27.1931
Evaluation completed in 0.28 seconds
(val) -35.2268 (test) -36.0556
🌸 New best epoch! 🌸

Epoch 29: 100%|██████████| 295/295 [00:02<00:00, 103.51it/s]

MAE (val set): 26.5931
Evaluation completed in 0.35 seconds
MAE (test set): 27.0157
Evaluation completed in 0.28 seconds
(val) -35.1417 (test) -35.8951
🌸 New best epoch! 🌸

Epoch 30: 100%|██████████| 295/295 [00:02<00:00, 103.50it/s]

MAE (val set): 26.4479
Evaluation completed in 0.34 seconds
MAE (test set): 26.9302
Evaluation completed in 0.28 seconds
(val) -35.0676 (test) -35.8005
🌸 New best epoch! 🌸

Epoch 31: 100%|██████████| 295/295 [00:02<00:00, 103.49it/s]

MAE (val set): 26.6241
Evaluation completed in 0.34 seconds
MAE (test set): 27.1250
Evaluation completed in 0.28 seconds
(val) -35.2458 (test) -36.0338

Epoch 32: 100%|██████████| 295/295 [00:02<00:00, 103.46it/s]

MAE (val set): 26.5382
Evaluation completed in 0.35 seconds
MAE (test set): 27.0627
Evaluation completed in 0.28 seconds
(val) -35.1342 (test) -35.9065

Epoch 33: 100%|██████████| 295/295 [00:02<00:00, 103.49it/s]

MAE (val set): 26.3649
Evaluation completed in 0.34 seconds
MAE (test set): 26.8285
Evaluation completed in 0.28 seconds
(val) -34.9664 (test) -35.7694
🌸 New best epoch! 🌸

Epoch 34: 100%|██████████| 295/295 [00:02<00:00, 103.48it/s]

MAE (val set): 26.9237
Evaluation completed in 0.34 seconds
MAE (test set): 27.3679
Evaluation completed in 0.28 seconds
(val) -35.3383 (test) -36.0696

Epoch 35: 100%|██████████| 295/295 [00:02<00:00, 103.46it/s]

MAE (val set): 26.3817
Evaluation completed in 0.34 seconds
MAE (test set): 26.7939
Evaluation completed in 0.28 seconds
(val) -34.9674 (test) -35.6970

Epoch 36: 100%|██████████| 295/295 [00:02<00:00, 103.48it/s]

MAE (val set): 26.5733
Evaluation completed in 0.34 seconds
MAE (test set): 27.0728
Evaluation completed in 0.28 seconds
(val) -35.0483 (test) -35.8278

Epoch 37: 100%|██████████| 295/295 [00:02<00:00, 103.47it/s]

MAE (val set): 26.8403
Evaluation completed in 0.34 seconds
MAE (test set): 27.2579
Evaluation completed in 0.28 seconds
(val) -35.2248 (test) -35.9382

Epoch 38: 100%|██████████| 295/295 [00:02<00:00, 103.46it/s]

MAE (val set): 26.6568
Evaluation completed in 0.34 seconds
MAE (test set): 27.1075
Evaluation completed in 0.28 seconds
(val) -35.1571 (test) -35.9032

Epoch 39: 100%|██████████| 295/295 [00:02<00:00, 103.45it/s]

MAE (val set): 27.2183
Evaluation completed in 0.35 seconds
MAE (test set): 27.6502
Evaluation completed in 0.28 seconds
(val) -35.5258 (test) -36.2024

Epoch 40: 100%|██████████| 295/295 [00:02<00:00, 103.42it/s]

MAE (val set): 26.9391
Evaluation completed in 0.35 seconds
MAE (test set): 27.3546
Evaluation completed in 0.28 seconds
(val) -35.3529 (test) -36.0056

Epoch 41: 100%|██████████| 295/295 [00:02<00:00, 103.43it/s]

MAE (val set): 26.5822
Evaluation completed in 0.34 seconds
MAE (test set): 27.0300
Evaluation completed in 0.28 seconds
(val) -35.1256 (test) -35.8238

Epoch 42: 100%|██████████| 295/295 [00:02<00:00, 103.43it/s]

MAE (val set): 26.4604
Evaluation completed in 0.34 seconds
MAE (test set): 26.9751
Evaluation completed in 0.28 seconds
(val) -35.0649 (test) -35.8133

Epoch 43: 100%|██████████| 295/295 [00:02<00:00, 103.43it/s]

MAE (val set): 26.4017
Evaluation completed in 0.34 seconds
MAE (test set): 26.9020
Evaluation completed in 0.28 seconds
(val) -35.0944 (test) -35.8609

Epoch 44: 100%|██████████| 295/295 [00:02<00:00, 103.40it/s]

MAE (val set): 26.6918
Evaluation completed in 0.35 seconds
MAE (test set): 27.1384
Evaluation completed in 0.28 seconds
(val) -35.1262 (test) -35.8420

Epoch 45: 100%|██████████| 295/295 [00:02<00:00, 103.43it/s]

MAE (val set): 26.5908
Evaluation completed in 0.34 seconds
MAE (test set): 27.0518
Evaluation completed in 0.28 seconds
(val) -35.0553 (test) -35.7785

Epoch 46: 100%|██████████| 295/295 [00:02<00:00, 103.43it/s]

MAE (val set): 26.2981
Evaluation completed in 0.34 seconds
MAE (test set): 26.7954
Evaluation completed in 0.28 seconds
(val) -34.8747 (test) -35.6310
🌸 New best epoch! 🌸

Epoch 47: 100%|██████████| 295/295 [00:02<00:00, 103.39it/s]

MAE (val set): 26.3297
Evaluation completed in 0.35 seconds
MAE (test set): 26.7959
Evaluation completed in 0.28 seconds
(val) -34.9400 (test) -35.6841

Epoch 48: 100%|██████████| 295/295 [00:02<00:00, 103.40it/s]

MAE (val set): 26.5526
Evaluation completed in 0.35 seconds
MAE (test set): 27.0546
Evaluation completed in 0.28 seconds
(val) -35.1280 (test) -35.8443

Epoch 49: 100%|██████████| 295/295 [00:02<00:00, 103.38it/s]

MAE (val set): 26.6559
Evaluation completed in 0.35 seconds
MAE (test set): 27.1275
Evaluation completed in 0.28 seconds
(val) -35.0779 (test) -35.8434

Epoch 50: 100%|██████████| 295/295 [00:02<00:00, 103.36it/s]

MAE (val set): 26.4320
Evaluation completed in 0.34 seconds
MAE (test set): 26.8917
Evaluation completed in 0.28 seconds
(val) -34.9967 (test) -35.7271

Epoch 51: 100%|██████████| 295/295 [00:02<00:00, 103.38it/s]

MAE (val set): 26.4888
Evaluation completed in 0.34 seconds
MAE (test set): 26.9476
Evaluation completed in 0.28 seconds
(val) -34.9279 (test) -35.6812

Epoch 52: 100%|██████████| 295/295 [00:02<00:00, 103.37it/s]

MAE (val set): 26.2007
Evaluation completed in 0.34 seconds
MAE (test set): 26.6762
Evaluation completed in 0.28 seconds
(val) -34.7755 (test) -35.5331
🌸 New best epoch! 🌸

Epoch 53: 100%|██████████| 295/295 [00:02<00:00, 103.39it/s]

MAE (val set): 26.6636
Evaluation completed in 0.34 seconds
MAE (test set): 27.1383
Evaluation completed in 0.28 seconds
(val) -35.1477 (test) -35.8801

Epoch 54: 100%|██████████| 295/295 [00:02<00:00, 103.39it/s]

MAE (val set): 26.7025
Evaluation completed in 0.35 seconds
MAE (test set): 27.1744
Evaluation completed in 0.28 seconds
(val) -35.1374 (test) -35.8657

Epoch 55: 100%|██████████| 295/295 [00:02<00:00, 103.40it/s]

MAE (val set): 26.4264
Evaluation completed in 0.34 seconds
MAE (test set): 26.9620
Evaluation completed in 0.28 seconds
(val) -35.0856 (test) -35.8542

Epoch 56: 100%|██████████| 295/295 [00:02<00:00, 103.32it/s]

MAE (val set): 26.5911
Evaluation completed in 0.34 seconds
MAE (test set): 27.0624
Evaluation completed in 0.28 seconds
(val) -35.1360 (test) -35.8313

Epoch 57: 100%|██████████| 295/295 [00:02<00:00, 103.40it/s]

MAE (val set): 26.5219
Evaluation completed in 0.35 seconds
MAE (test set): 27.0024
Evaluation completed in 0.28 seconds
(val) -35.0574 (test) -35.7965

Epoch 58: 100%|██████████| 295/295 [00:02<00:00, 103.38it/s]

MAE (val set): 26.3018
Evaluation completed in 0.34 seconds
MAE (test set): 26.7534
Evaluation completed in 0.28 seconds
(val) -34.7673 (test) -35.5184
🌸 New best epoch! 🌸

Epoch 59: 100%|██████████| 295/295 [00:02<00:00, 103.38it/s]

MAE (val set): 26.1795
Evaluation completed in 0.34 seconds
MAE (test set): 26.5945
Evaluation completed in 0.28 seconds
(val) -34.8282 (test) -35.5071

Epoch 60: 100%|██████████| 295/295 [00:02<00:00, 103.39it/s]

MAE (val set): 26.4579
Evaluation completed in 0.34 seconds
MAE (test set): 26.9607
Evaluation completed in 0.28 seconds
(val) -35.1288 (test) -35.9079

Epoch 61: 100%|██████████| 295/295 [00:02<00:00, 103.38it/s]

MAE (val set): 26.3645
Evaluation completed in 0.34 seconds
MAE (test set): 26.8283
Evaluation completed in 0.28 seconds
(val) -34.8343 (test) -35.5471

Epoch 62: 100%|██████████| 295/295 [00:02<00:00, 103.36it/s]

MAE (val set): 26.3880
Evaluation completed in 0.34 seconds
MAE (test set): 26.8843
Evaluation completed in 0.28 seconds
(val) -34.8695 (test) -35.6480

Epoch 63: 100%|██████████| 295/295 [00:02<00:00, 103.37it/s]

MAE (val set): 26.1401
Evaluation completed in 0.35 seconds
MAE (test set): 26.6311
Evaluation completed in 0.28 seconds
(val) -34.7870 (test) -35.5763

Epoch 64: 100%|██████████| 295/295 [00:02<00:00, 103.40it/s]

MAE (val set): 26.5988
Evaluation completed in 0.35 seconds
MAE (test set): 27.0330
Evaluation completed in 0.28 seconds
(val) -35.1049 (test) -35.7954

Epoch 65: 100%|██████████| 295/295 [00:02<00:00, 103.36it/s]

MAE (val set): 26.3624
Evaluation completed in 0.35 seconds
MAE (test set): 26.8707
Evaluation completed in 0.28 seconds
(val) -35.0376 (test) -35.7661

Epoch 66: 100%|██████████| 295/295 [00:02<00:00, 103.36it/s]

MAE (val set): 26.2878
Evaluation completed in 0.34 seconds
MAE (test set): 26.7254
Evaluation completed in 0.28 seconds
(val) -34.8550 (test) -35.5296

Epoch 67: 100%|██████████| 295/295 [00:02<00:00, 103.35it/s]

MAE (val set): 26.1518
Evaluation completed in 0.34 seconds
MAE (test set): 26.6353
Evaluation completed in 0.28 seconds
(val) -34.7598 (test) -35.4834
🌸 New best epoch! 🌸

Epoch 68: 100%|██████████| 295/295 [00:02<00:00, 103.34it/s]

MAE (val set): 26.1783
Evaluation completed in 0.34 seconds
MAE (test set): 26.7130
Evaluation completed in 0.28 seconds
(val) -34.7962 (test) -35.5642

Epoch 69: 100%|██████████| 295/295 [00:02<00:00, 103.33it/s]

MAE (val set): 26.1059
Evaluation completed in 0.34 seconds
MAE (test set): 26.6320
Evaluation completed in 0.28 seconds
(val) -34.7884 (test) -35.5899

Epoch 70: 100%|██████████| 295/295 [00:02<00:00, 103.35it/s]

MAE (val set): 26.3910
Evaluation completed in 0.34 seconds
MAE (test set): 26.8674
Evaluation completed in 0.28 seconds
(val) -34.8749 (test) -35.5992

Epoch 71: 100%|██████████| 295/295 [00:02<00:00, 103.33it/s]

MAE (val set): 26.0724
Evaluation completed in 0.35 seconds
MAE (test set): 26.5748
Evaluation completed in 0.28 seconds
(val) -34.6940 (test) -35.4774
🌸 New best epoch! 🌸

Epoch 72: 100%|██████████| 295/295 [00:02<00:00, 103.34it/s]

MAE (val set): 26.2267
Evaluation completed in 0.35 seconds
MAE (test set): 26.6701
Evaluation completed in 0.28 seconds
(val) -34.7601 (test) -35.4672

Epoch 73: 100%|██████████| 295/295 [00:02<00:00, 103.35it/s]

MAE (val set): 26.2156
Evaluation completed in 0.35 seconds
MAE (test set): 26.6713
Evaluation completed in 0.28 seconds
(val) -34.7676 (test) -35.4925

Epoch 74: 100%|██████████| 295/295 [00:02<00:00, 103.34it/s]

MAE (val set): 26.2739
Evaluation completed in 0.35 seconds
MAE (test set): 26.7503
Evaluation completed in 0.28 seconds
(val) -34.9064 (test) -35.6456

Epoch 75: 100%|██████████| 295/295 [00:02<00:00, 103.37it/s]

MAE (val set): 26.2976
Evaluation completed in 0.35 seconds
MAE (test set): 26.7955
Evaluation completed in 0.28 seconds
(val) -34.8479 (test) -35.6084

Epoch 76: 100%|██████████| 295/295 [00:02<00:00, 103.34it/s]

MAE (val set): 26.2097
Evaluation completed in 0.34 seconds
MAE (test set): 26.7281
Evaluation completed in 0.28 seconds
(val) -34.7867 (test) -35.5440

Epoch 77: 100%|██████████| 295/295 [00:02<00:00, 103.32it/s]

MAE (val set): 26.6176
Evaluation completed in 0.35 seconds
MAE (test set): 27.0619
Evaluation completed in 0.28 seconds
(val) -35.0462 (test) -35.7127

Epoch 78: 100%|██████████| 295/295 [00:02<00:00, 103.38it/s]

MAE (val set): 26.5719
Evaluation completed in 0.35 seconds
MAE (test set): 26.9946
Evaluation completed in 0.28 seconds
(val) -35.0200 (test) -35.6945

Epoch 79: 100%|██████████| 295/295 [00:02<00:00, 103.35it/s]

MAE (val set): 26.3913
Evaluation completed in 0.35 seconds
MAE (test set): 26.8114
Evaluation completed in 0.28 seconds
(val) -34.8145 (test) -35.5281

Epoch 80: 100%|██████████| 295/295 [00:02<00:00, 103.31it/s]

MAE (val set): 26.2972
Evaluation completed in 0.34 seconds
MAE (test set): 26.7725
Evaluation completed in 0.28 seconds
(val) -34.9341 (test) -35.6420

Epoch 81: 100%|██████████| 295/295 [00:02<00:00, 103.29it/s]

MAE (val set): 26.3477
Evaluation completed in 0.34 seconds
MAE (test set): 26.8735
Evaluation completed in 0.28 seconds
(val) -34.8952 (test) -35.6651

Epoch 82: 100%|██████████| 295/295 [00:02<00:00, 103.34it/s]

MAE (val set): 26.2878
Evaluation completed in 0.34 seconds
MAE (test set): 26.7483
Evaluation completed in 0.28 seconds
(val) -34.7940 (test) -35.5008

Epoch 83: 100%|██████████| 295/295 [00:02<00:00, 103.29it/s]

MAE (val set): 26.1217
Evaluation completed in 0.35 seconds
MAE (test set): 26.6063
Evaluation completed in 0.28 seconds
(val) -34.6479 (test) -35.3887
🌸 New best epoch! 🌸

Epoch 84: 100%|██████████| 295/295 [00:02<00:00, 103.33it/s]

MAE (val set): 26.1335
Evaluation completed in 0.34 seconds
MAE (test set): 26.6410
Evaluation completed in 0.28 seconds
(val) -34.7167 (test) -35.4714

Epoch 85: 100%|██████████| 295/295 [00:02<00:00, 103.33it/s]

MAE (val set): 26.2556
Evaluation completed in 0.34 seconds
MAE (test set): 26.7220
Evaluation completed in 0.28 seconds
(val) -34.7312 (test) -35.4526

Epoch 86: 100%|██████████| 295/295 [00:02<00:00, 103.30it/s]

MAE (val set): 26.5228
Evaluation completed in 0.34 seconds
MAE (test set): 26.9888
Evaluation completed in 0.28 seconds
(val) -34.9217 (test) -35.6275

Epoch 87: 100%|██████████| 295/295 [00:02<00:00, 103.28it/s]

MAE (val set): 26.2414
Evaluation completed in 0.34 seconds
MAE (test set): 26.7380
Evaluation completed in 0.28 seconds
(val) -34.7826 (test) -35.5515

Epoch 88: 100%|██████████| 295/295 [00:02<00:00, 103.27it/s]

MAE (val set): 26.1412
Evaluation completed in 0.34 seconds
MAE (test set): 26.6029
Evaluation completed in 0.28 seconds
(val) -34.6978 (test) -35.4575

Epoch 89: 100%|██████████| 295/295 [00:02<00:00, 103.29it/s]

MAE (val set): 26.3295
Evaluation completed in 0.34 seconds
MAE (test set): 26.8269
Evaluation completed in 0.28 seconds
(val) -34.9972 (test) -35.7678

Epoch 90: 100%|██████████| 295/295 [00:02<00:00, 103.28it/s]

MAE (val set): 26.3907
Evaluation completed in 0.34 seconds
MAE (test set): 26.8346
Evaluation completed in 0.28 seconds
(val) -34.8702 (test) -35.5356

Epoch 91: 100%|██████████| 295/295 [00:02<00:00, 103.27it/s]

MAE (val set): 26.3019
Evaluation completed in 0.34 seconds
MAE (test set): 26.8058
Evaluation completed in 0.28 seconds
(val) -34.9037 (test) -35.6351

Epoch 92: 100%|██████████| 295/295 [00:02<00:00, 103.17it/s]

MAE (val set): 26.2585
Evaluation completed in 0.34 seconds
MAE (test set): 26.7249
Evaluation completed in 0.28 seconds
(val) -34.7490 (test) -35.4827

Epoch 93: 100%|██████████| 295/295 [00:02<00:00, 103.27it/s]

MAE (val set): 26.3498
Evaluation completed in 0.34 seconds
MAE (test set): 26.7701
Evaluation completed in 0.28 seconds
(val) -34.7824 (test) -35.4546

Epoch 94: 100%|██████████| 295/295 [00:02<00:00, 103.23it/s]

MAE (val set): 26.3767
Evaluation completed in 0.34 seconds
MAE (test set): 26.8650
Evaluation completed in 0.28 seconds
(val) -34.9287 (test) -35.6490

Epoch 95: 100%|██████████| 295/295 [00:02<00:00, 103.26it/s]

MAE (val set): 26.0831
Evaluation completed in 0.34 seconds
MAE (test set): 26.5468
Evaluation completed in 0.28 seconds
(val) -34.6405 (test) -35.3543
🌸 New best epoch! 🌸

Epoch 96: 100%|██████████| 295/295 [00:02<00:00, 103.23it/s]

MAE (val set): 26.1855
Evaluation completed in 0.34 seconds
MAE (test set): 26.6242
Evaluation completed in 0.28 seconds
(val) -34.7114 (test) -35.4284

Epoch 97: 100%|██████████| 295/295 [00:02<00:00, 103.23it/s]

MAE (val set): 26.4500
Evaluation completed in 0.34 seconds
MAE (test set): 26.9195
Evaluation completed in 0.28 seconds
(val) -34.9215 (test) -35.6458

Epoch 98: 100%|██████████| 295/295 [00:02<00:00, 103.15it/s]

MAE (val set): 26.1458
Evaluation completed in 0.34 seconds
MAE (test set): 26.6671
Evaluation completed in 0.28 seconds
(val) -34.8875 (test) -35.6632

Epoch 99: 100%|██████████| 295/295 [00:02<00:00, 103.23it/s]

MAE (val set): 26.2660
Evaluation completed in 0.34 seconds
MAE (test set): 26.7481
Evaluation completed in 0.28 seconds
(val) -34.8471 (test) -35.5843

Epoch 100: 100%|██████████| 295/295 [00:02<00:00, 103.23it/s]

MAE (val set): 26.1459
Evaluation completed in 0.34 seconds
MAE (test set): 26.6003
Evaluation completed in 0.28 seconds
(val) -34.7000 (test) -35.4256

Epoch 101: 100%|██████████| 295/295 [00:02<00:00, 103.28it/s]

MAE (val set): 26.2835
Evaluation completed in 0.35 seconds
MAE (test set): 26.7332
Evaluation completed in 0.28 seconds
(val) -34.7869 (test) -35.4616

Epoch 102: 100%|██████████| 295/295 [00:02<00:00, 103.16it/s]

MAE (val set): 26.0675
Evaluation completed in 0.34 seconds
MAE (test set): 26.5603
Evaluation completed in 0.28 seconds
(val) -34.6771 (test) -35.4098

Epoch 103: 100%|██████████| 295/295 [00:02<00:00, 103.30it/s]

MAE (val set): 26.2049
Evaluation completed in 0.34 seconds
MAE (test set): 26.6346
Evaluation completed in 0.28 seconds
(val) -34.7128 (test) -35.4129

Epoch 104: 100%|██████████| 295/295 [00:02<00:00, 103.13it/s]

MAE (val set): 26.1772
Evaluation completed in 0.34 seconds
MAE (test set): 26.6828
Evaluation completed in 0.28 seconds
(val) -34.7623 (test) -35.5160

Epoch 105: 100%|██████████| 295/295 [00:02<00:00, 103.22it/s]

MAE (val set): 26.0311
Evaluation completed in 0.34 seconds
MAE (test set): 26.4534
Evaluation completed in 0.28 seconds
(val) -34.6350 (test) -35.3352
🌸 New best epoch! 🌸

Epoch 106: 100%|██████████| 295/295 [00:02<00:00, 103.24it/s]

MAE (val set): 26.1374
Evaluation completed in 0.34 seconds
MAE (test set): 26.5737
Evaluation completed in 0.28 seconds
(val) -34.7033 (test) -35.3892

Epoch 107: 100%|██████████| 295/295 [00:02<00:00, 103.13it/s]

MAE (val set): 26.1380
Evaluation completed in 0.34 seconds
MAE (test set): 26.5946
Evaluation completed in 0.28 seconds
(val) -34.6987 (test) -35.4276

Epoch 108: 100%|██████████| 295/295 [00:02<00:00, 103.16it/s]

MAE (val set): 26.1594
Evaluation completed in 0.34 seconds
MAE (test set): 26.6384
Evaluation completed in 0.28 seconds
(val) -34.7559 (test) -35.5166

Epoch 109: 100%|██████████| 295/295 [00:02<00:00, 103.19it/s]

MAE (val set): 26.1239
Evaluation completed in 0.35 seconds
MAE (test set): 26.6038
Evaluation completed in 0.28 seconds
(val) -34.7085 (test) -35.4265

Epoch 110: 100%|██████████| 295/295 [00:02<00:00, 103.17it/s]

MAE (val set): 26.1592
Evaluation completed in 0.34 seconds
MAE (test set): 26.6333
Evaluation completed in 0.28 seconds
(val) -34.7192 (test) -35.4530

Epoch 111: 100%|██████████| 295/295 [00:02<00:00, 103.29it/s]

MAE (val set): 26.2091
Evaluation completed in 0.34 seconds
MAE (test set): 26.6846
Evaluation completed in 0.28 seconds
(val) -34.7637 (test) -35.4778

Epoch 112: 100%|██████████| 295/295 [00:02<00:00, 103.20it/s]

MAE (val set): 26.0704
Evaluation completed in 0.34 seconds
MAE (test set): 26.5120
Evaluation completed in 0.28 seconds
(val) -34.6322 (test) -35.3531
🌸 New best epoch! 🌸

Epoch 113: 100%|██████████| 295/295 [00:02<00:00, 103.22it/s]

MAE (val set): 26.0441
Evaluation completed in 0.34 seconds
MAE (test set): 26.5083
Evaluation completed in 0.28 seconds
(val) -34.6329 (test) -35.3834

Epoch 114: 100%|██████████| 295/295 [00:02<00:00, 103.20it/s]

MAE (val set): 26.0984
Evaluation completed in 0.34 seconds
MAE (test set): 26.5407
Evaluation completed in 0.28 seconds
(val) -34.6584 (test) -35.3569

Epoch 115: 100%|██████████| 295/295 [00:02<00:00, 103.22it/s]

MAE (val set): 26.0050
Evaluation completed in 0.34 seconds
MAE (test set): 26.4450
Evaluation completed in 0.28 seconds
(val) -34.5819 (test) -35.2765
🌸 New best epoch! 🌸

Epoch 116: 100%|██████████| 295/295 [00:02<00:00, 103.20it/s]

MAE (val set): 26.2593
Evaluation completed in 0.34 seconds
MAE (test set): 26.6794
Evaluation completed in 0.28 seconds
(val) -34.7824 (test) -35.4436

Epoch 117: 100%|██████████| 295/295 [00:02<00:00, 103.24it/s]

MAE (val set): 26.3997
Evaluation completed in 0.35 seconds
MAE (test set): 26.8023
Evaluation completed in 0.28 seconds
(val) -34.8526 (test) -35.4949

Epoch 118: 100%|██████████| 295/295 [00:02<00:00, 103.24it/s]

MAE (val set): 26.1059
Evaluation completed in 0.35 seconds
MAE (test set): 26.5353
Evaluation completed in 0.28 seconds
(val) -34.6365 (test) -35.3157

Epoch 119: 100%|██████████| 295/295 [00:02<00:00, 103.16it/s]

MAE (val set): 26.4335
Evaluation completed in 0.34 seconds
MAE (test set): 26.8423
Evaluation completed in 0.28 seconds
(val) -34.8622 (test) -35.4873

Epoch 120: 100%|██████████| 295/295 [00:02<00:00, 103.24it/s]

MAE (val set): 26.1386
Evaluation completed in 0.34 seconds
MAE (test set): 26.5667
Evaluation completed in 0.28 seconds
(val) -34.6741 (test) -35.3715

Epoch 121: 100%|██████████| 295/295 [00:02<00:00, 103.25it/s]

MAE (val set): 26.3033
Evaluation completed in 0.34 seconds
MAE (test set): 26.7054
Evaluation completed in 0.28 seconds
(val) -34.7843 (test) -35.4255

Epoch 122: 100%|██████████| 295/295 [00:02<00:00, 103.22it/s]

MAE (val set): 26.5918
Evaluation completed in 0.34 seconds
MAE (test set): 26.9883
Evaluation completed in 0.28 seconds
(val) -34.9424 (test) -35.5769

Epoch 123: 100%|██████████| 295/295 [00:02<00:00, 103.20it/s]

MAE (val set): 26.1944
Evaluation completed in 0.34 seconds
MAE (test set): 26.6581
Evaluation completed in 0.28 seconds
(val) -34.6947 (test) -35.4142

Epoch 124: 100%|██████████| 295/295 [00:02<00:00, 103.28it/s]

MAE (val set): 26.4818
Evaluation completed in 0.34 seconds
MAE (test set): 26.9324
Evaluation completed in 0.28 seconds
(val) -35.0667 (test) -35.7569

Epoch 125: 100%|██████████| 295/295 [00:02<00:00, 103.18it/s]

MAE (val set): 26.2232
Evaluation completed in 0.34 seconds
MAE (test set): 26.6558
Evaluation completed in 0.28 seconds
(val) -34.8184 (test) -35.4745

Epoch 126: 100%|██████████| 295/295 [00:02<00:00, 103.24it/s]

MAE (val set): 26.2031
Evaluation completed in 0.34 seconds
MAE (test set): 26.5790
Evaluation completed in 0.28 seconds
(val) -34.6723 (test) -35.3031

Epoch 127: 100%|██████████| 295/295 [00:02<00:00, 103.16it/s]

MAE (val set): 26.2158
Evaluation completed in 0.34 seconds
MAE (test set): 26.6837
Evaluation completed in 0.28 seconds
(val) -34.8099 (test) -35.5690

Epoch 128: 100%|██████████| 295/295 [00:02<00:00, 103.26it/s]

MAE (val set): 26.1139
Evaluation completed in 0.35 seconds
MAE (test set): 26.5449
Evaluation completed in 0.28 seconds
(val) -34.6859 (test) -35.3624

Epoch 129: 100%|██████████| 295/295 [00:02<00:00, 103.24it/s]

MAE (val set): 26.0894
Evaluation completed in 0.35 seconds
MAE (test set): 26.4882
Evaluation completed in 0.28 seconds
(val) -34.6223 (test) -35.2887

Epoch 130: 100%|██████████| 295/295 [00:02<00:00, 103.18it/s]

MAE (val set): 26.3547
Evaluation completed in 0.34 seconds
MAE (test set): 26.8357
Evaluation completed in 0.28 seconds
(val) -34.9058 (test) -35.6491

Epoch 131: 100%|██████████| 295/295 [00:02<00:00, 103.22it/s]

MAE (val set): 26.1555
Evaluation completed in 0.34 seconds
MAE (test set): 26.5773
Evaluation completed in 0.28 seconds
(val) -34.6609 (test) -35.3426

Epoch 132: 100%|██████████| 295/295 [00:02<00:00, 103.31it/s]

MAE (val set): 25.9880
Evaluation completed in 0.34 seconds
MAE (test set): 26.4232
Evaluation completed in 0.28 seconds
(val) -34.5992 (test) -35.2957


Result:
{'val': -34.58191630819314, 'test': -35.27654419458488, 'epoch': 115}

In [66]:
print('\n\nResult:')
print(best)

Result:
{'val': -34.58191630819314, 'test': -35.27654419458488, 'epoch': 115}

In [67]:
# >>> Dataset.
TaskType = Literal['regression', 'binclass', 'multiclass']

# Regression.
task_type: TaskType = 'regression'
n_classes = None
dataset = joined_df
X_cont: np.ndarray = joined_df.iloc[:, :-1].to_numpy()
Y: np.ndarray = joined_df.iloc[:, -1].to_numpy()

task_is_regression = task_type == 'regression'

# >>> Continuous features.
X_cont: np.ndarray = X_cont.astype(np.float32)
n_cont_features = X_cont.shape[1]

# >>> Labels.
if task_type == 'regression':
    Y = Y.astype(np.float32)
else:
    assert n_classes is not None
    Y = Y.astype(np.int64)
    assert set(Y.tolist()) == set(
        range(n_classes)
    ), 'Classification labels must form the range [0, 1, ..., n_classes - 1]'

# >>> Split the dataset.
all_idx = np.arange(len(Y))
trainval_idx, test_idx = sklearn.model_selection.train_test_split(
    all_idx, train_size=0.8
)
train_idx, val_idx = sklearn.model_selection.train_test_split(
    trainval_idx, train_size=0.8
)
data_numpy = {
    'train': {'x_cont': X_cont[train_idx], 'y': Y[train_idx]},
    'val': {'x_cont': X_cont[val_idx], 'y': Y[val_idx]},
    'test': {'x_cont': X_cont[test_idx], 'y': Y[test_idx]},
}

X_cont_train_numpy = data_numpy['train']['x_cont']
noise = (
    np.random.default_rng(0)
    .normal(0.0, 1e-5, X_cont_train_numpy.shape)
    .astype(X_cont_train_numpy.dtype)
)
preprocessing = sklearn.preprocessing.QuantileTransformer(
    n_quantiles=max(min(len(train_idx) // 30, 1000), 10),
    output_distribution='normal',
    subsample=10**9,
).fit(X_cont_train_numpy + noise)
del X_cont_train_numpy

# Apply the preprocessing.
for part in data_numpy:
    data_numpy[part]['x_cont'] = preprocessing.transform(data_numpy[part]['x_cont'])


# Label preprocessing.
class RegressionLabelStats(NamedTuple):
    mean: float
    std: float


Y_train = data_numpy['train']['y'].copy()
if task_type == 'regression':
    # For regression tasks, it is highly recommended to standardize the training labels.
    regression_label_stats = RegressionLabelStats(
        Y_train.mean().item(), Y_train.std().item()
    )
    Y_train = (Y_train - regression_label_stats.mean) / regression_label_stats.std
else:
    regression_label_stats = None

data = {
    part: {k: torch.as_tensor(v, device=device) for k, v in data_numpy[part].items()}
    for part in data_numpy
}

Y_train = torch.as_tensor(Y_train, device=device)
if task_type == 'regression':
    for part in data:
        data[part]['y'] = data[part]['y'].float()
    Y_train = Y_train.float()
    
amp_dtype = (
    torch.bfloat16
    if torch.cuda.is_available() and torch.cuda.is_bf16_supported()
    else torch.float16
    if torch.cuda.is_available()
    else None
)
# Changing False to True will result in faster training on compatible hardware.
amp_enabled = False and amp_dtype is not None
grad_scaler = torch.cuda.amp.GradScaler() if amp_dtype is torch.float16 else None  # type: ignore

# torch.compile
compile_model = False

# fmt: off
print(
    f'Device:        {device.type.upper()}'
    f'\nAMP:           {amp_enabled} (dtype: {amp_dtype})'
    f'\ntorch.compile: {compile_model}'
)
# fmt: on

Device:        CUDA
AMP:           False (dtype: torch.bfloat16)
torch.compile: False

In [ ]:
# Choose one of the two configurations below.

# TabM
arch_type = 'tabm'
bins = None

model = Model(
    n_num_features=n_cont_features,
    cat_cardinalities=[], # zero categorical data
    n_classes=n_classes,
    backbone={
        'type': 'MLP',
        'n_blocks': 3 if bins is None else 2,
        'd_block': 512,
        'dropout': 0.1,
    },
    bins=bins,
    num_embeddings=(
        None
        if bins is None
        else {
            'type': 'PiecewiseLinearEmbeddings',
            'd_embedding': 16,
            'activation': False,
            'version': 'B',
        }
    ),
    arch_type=arch_type,
    k=32,
    share_training_batches=True,
).to(device)
optimizer = torch.optim.AdamW(make_parameter_groups(model), lr=2e-3, weight_decay=3e-4)

if compile_model:
    # NOTE
    # `torch.compile` is intentionally called without the `mode` argument
    # (mode="reduce-overhead" caused issues during training with torch==2.0.1).
    model = torch.compile(model)
    evaluation_mode = torch.no_grad
else:
    evaluation_mode = torch.inference_mode
    
@torch.autocast(device.type, enabled=amp_enabled, dtype=amp_dtype)  # type: ignore[code]
def apply_model(part: str, idx: Tensor) -> Tensor:
    return (
        model(
            data[part]['x_cont'][idx],
            data[part]['x_cat'][idx] if 'x_cat' in data[part] else None,
        )
        .squeeze(-1)  # Remove the last dimension for regression tasks.
        .float()
    )


base_loss_fn = F.mse_loss if task_type == 'regression' else F.cross_entropy


def loss_fn(y_pred: Tensor, y_true: Tensor) -> Tensor:
    # TabM produces k predictions. Each of them must be trained separately.
    # (regression)     y_pred.shape == (batch_size, k)
    # (classification) y_pred.shape == (batch_size, k, n_classes)
    k = y_pred.shape[-1 if task_type == 'regression' else -2]
    return base_loss_fn(
        y_pred.flatten(0, 1),
        y_true.repeat_interleave(k) if model.share_training_batches else y_true,
    )


@evaluation_mode()
def evaluate(part: str) -> float:
    import time  # Import time module for timing
    start_time = time.time()  # Start timer
    
    model.eval()

    # When using torch.compile, you may need to reduce the evaluation batch size.
    eval_batch_size = 8096
    y_pred: np.ndarray = (
        torch.cat(
            [
                apply_model(part, idx)
                for idx in torch.arange(len(data[part]['y']), device=device).split(
                    eval_batch_size
                )
            ]
        )
        .cpu()
        .numpy()
    )
    if task_type == 'regression':
        # Transform the predictions back to the original label space.
        assert regression_label_stats is not None
        y_pred = y_pred * regression_label_stats.std + regression_label_stats.mean

    # Compute the mean of the k predictions.
    if task_type != 'regression':
        # For classification, the mean must be computed in the probabily space.
        y_pred = scipy.special.softmax(y_pred, axis=-1)
    y_pred = y_pred.mean(1)

    y_true = data[part]['y'].cpu().numpy()
    mae = sklearn.metrics.mean_absolute_error(y_true, y_pred)
    print(f'MAE ({part} set): {mae:.4f}')  # [ADDED MAE PRINT]
    
    score = (
        -(sklearn.metrics.mean_squared_error(y_true, y_pred) ** 0.5)
        if task_type == 'regression'
        else sklearn.metrics.accuracy_score(y_true, y_pred.argmax(1))
    )
    
    end_time = time.time()  # End timer
    elapsed_time = end_time - start_time  # Calculate elapsed time
    print(f'Evaluation completed in {elapsed_time:.2f} seconds')  # Print timing info
    
    return float(score)  # The higher -- the better.


print(f'Test score before training: {evaluate("test"):.4f}')

In [68]:
import optuna
from optuna.samplers import TPESampler

In [70]:
# TabM
arch_type = 'tabm'
bins = None
def train_and_evaluate(model, optimizer):
    n_epochs = 1_000_000_000
    patience = 16

    train_size = len(train_idx)
    batch_size = 256
    epoch_size = math.ceil(train_size / batch_size)
    best = {
        'val': -math.inf,
        'test': -math.inf,
        'epoch': -1,
    }
    # Early stopping: the training stops when
    # there are more than `patience` consequtive bad updates.
    patience = 16
    remaining_patience = patience

    print('-' * 88 + '\n')
    for epoch in range(n_epochs):
        batches = (
            torch.randperm(train_size, device=device).split(batch_size)
            if model.share_training_batches
            else [
                x.transpose(0, 1).flatten()
                for x in torch.rand((model.k, train_size), device=device)
                .argsort(dim=1)
                .split(batch_size, dim=1)
            ]
        )
        for batch_idx in tqdm(batches, desc=f'Epoch {epoch}'):
            model.train()
            optimizer.zero_grad()
            loss = loss_fn(apply_model('train', batch_idx), Y_train[batch_idx])
            if grad_scaler is None:
                loss.backward()
                optimizer.step()
            else:
                grad_scaler.scale(loss).backward()  # type: ignore
                grad_scaler.step(optimizer)
                grad_scaler.update()

        val_score = evaluate('val')
        test_score = evaluate('test')
        print(f'(val) {val_score:.4f} (test) {test_score:.4f}')

        if val_score > best['val']:
            print('🌸 New best epoch! 🌸')
            best = {'val': val_score, 'test': test_score, 'epoch': epoch}
            remaining_patience = patience
        else:
            remaining_patience -= 1

        if remaining_patience < 0:
            break

        print()

    print('\n\nResult:')
    print(best)